# <center>ANÁLISE DE VAGAS DE TECNOLOGIA E CANDIDATURAS

## <center>Importação e Exploração dos dados

In [886]:
# Importanto bibliotecas

import pandas as pd
import numpy as np
import random
import plotly.express as px
import plotly.graph_objects as go
import re

In [887]:
# Importando a base de dados

df = pd.read_csv('vagas.csv')
df.head(3)

,Title,basecard_fulllink_URL,hiddennestedlink_URL,hiddennestedlink,Location,resultbenefits_text,Date,Título,Empresa,Localizacao,Divulgacao,Candidaturas,Descricao,Senioridade,Tipo,Funcao,Setor,Current_time,palavra_chave
0,Desenvolvedor(a) Frontend Junior,https://br.linkedin.com/jobs/view/desenvolvedo...,https://br.linkedin.com/company/zenvia-inc?trk...,ZENVIA,"São Paulo, SP",NaN,2024-01-10,Desenvolvedor(a) Frontend Junior,ZENVIA,"São Paulo, SP",Há 15 horas,Mais de 200 candidaturas,O time de Attraction tem a missão de analisar ...,Assistente,Tempo integral,Engenharia e Tecnologia da informação,"Tecnologia, Informação e Internet",2024-01-11,Desenvolvedor
1,Desenvolvedor DataViz Jr - Hibrido - Faria Lim...,https://br.linkedin.com/jobs/view/desenvolvedo...,https://br.linkedin.com/company/iterative-?trk...,Iterative;,"São Paulo, SP",NaN,2023-12-27,Desenvolvedor DataViz Jr - Hibrido - Faria Lim...,Iterative;,"São Paulo, SP",NaN,Seja um dos 25 primeiros a se candidatar,Data Viz Jr.\nResponsabilidades\nAtuar como su...,Pleno-sênior,Tempo integral,Engenharia e Tecnologia da informação,Segurança de redes e computadores,2024-01-11,Desenvolvedor
2,Estágio - Desenvolvedor(a) Java,https://br.linkedin.com/jobs/view/est%C3%A1gio...,https://br.linkedin.com/company/meisters-solut...,Meisters Solutions,"Curitiba, PR",NaN,2024-01-08,Estágio - Desenvolvedor(a) Java,Meisters Solutions,"Curitiba, PR",NaN,NaN,Nível: Estagiário\nCursos de: Análise e desenv...,Estágio,Tempo integral,Engenharia e Tecnologia da informação,Desenvolvimento de software,2024-01-11,Desenvolvedor

In [888]:
# Verificando o tamanho do dataset
print(f'Tamanho do dataset: {df.shape[0]} linhas e {df.shape[1]} colunas')

Tamanho do dataset: 83959 linhas e 19 colunas

In [889]:
# Verificando os tipos de dados
print('Tipos de dados:')
print(df.dtypes)

Tipos de dados:
Title                    object
basecard_fulllink_URL    object
hiddennestedlink_URL     object
hiddennestedlink         object
Location                 object
resultbenefits_text      object
Date                     object
Título                   object
Empresa                  object
Localizacao              object
Divulgacao               object
Candidaturas             object
Descricao                object
Senioridade              object
Tipo                     object
Funcao                   object
Setor                    object
Current_time             object
palavra_chave            object
dtype: object

In [890]:
# Verificando se há valores nulos
print('Valores nulos:')
print(df.isnull().sum())

Valores nulos:
Title                        0
basecard_fulllink_URL        0
hiddennestedlink_URL         0
hiddennestedlink             1
Location                     0
resultbenefits_text      14078
Date                         0
Título                      26
Empresa                    194
Localizacao                193
Divulgacao                7213
Candidaturas             37100
Descricao                 6673
Senioridade               5239
Tipo                     78686
Funcao                    5547
Setor                     5548
Current_time                 9
palavra_chave                9
dtype: int64

In [891]:
df.describe()

,Title,basecard_fulllink_URL,hiddennestedlink_URL,hiddennestedlink,Location,resultbenefits_text,Date,Título,Empresa,Localizacao,Divulgacao,Candidaturas,Descricao,Senioridade,Tipo,Funcao,Setor,Current_time,palavra_chave
count,83959,83959,83959,83958,83959,69881,83959,83933,83765,83766,76746,46859,77286,78720,5273,78412,78411,83950,83950
unique,4087,8533,2415,2410,378,2,113,4119,2344,375,55,172,5504,4,7,305,377,57013,20
top,Desenvolvedor,https://br.linkedin.com/jobs/view/dba-at-bne-b...,https://br.linkedin.com/company/bneempregos?tr...,BNE - Banco Nacional de Empregos,"São Paulo, SP",Seja um dos primeiros a se candidatar,2024-01-31,Desenvolvedor,BNE - Banco Nacional de Empregos,"São Paulo, SP",Há 1 semana,Seja um dos 25 primeiros a se candidatar,Location: Remote WFH All Latin American Candid...,Assistente,Tempo integral,Engenharia e Tecnologia da informação,Atividades dos serviços de tecnologia da infor...,2024-01-31,DBA
freq,5811,32,9472,9471,25454,46158,6781,5807,9442,25295,17876,29229,273,41347,4734,23580,11673,7822,10232

## <center>Tratamento dos Dados

### Padronizando colunas

In [892]:
# Renomeando colunas redundantes ou desnecessárias
df.drop(columns=['Título', 'Empresa', 'Localizacao', 'Divulgacao', 'resultbenefits_text'], inplace=True)
df.head(3)

,Title,basecard_fulllink_URL,hiddennestedlink_URL,hiddennestedlink,Location,Date,Candidaturas,Descricao,Senioridade,Tipo,Funcao,Setor,Current_time,palavra_chave
0,Desenvolvedor(a) Frontend Junior,https://br.linkedin.com/jobs/view/desenvolvedo...,https://br.linkedin.com/company/zenvia-inc?trk...,ZENVIA,"São Paulo, SP",2024-01-10,Mais de 200 candidaturas,O time de Attraction tem a missão de analisar ...,Assistente,Tempo integral,Engenharia e Tecnologia da informação,"Tecnologia, Informação e Internet",2024-01-11,Desenvolvedor
1,Desenvolvedor DataViz Jr - Hibrido - Faria Lim...,https://br.linkedin.com/jobs/view/desenvolvedo...,https://br.linkedin.com/company/iterative-?trk...,Iterative;,"São Paulo, SP",2023-12-27,Seja um dos 25 primeiros a se candidatar,Data Viz Jr.\nResponsabilidades\nAtuar como su...,Pleno-sênior,Tempo integral,Engenharia e Tecnologia da informação,Segurança de redes e computadores,2024-01-11,Desenvolvedor
2,Estágio - Desenvolvedor(a) Java,https://br.linkedin.com/jobs/view/est%C3%A1gio...,https://br.linkedin.com/company/meisters-solut...,Meisters Solutions,"Curitiba, PR",2024-01-08,NaN,Nível: Estagiário\nCursos de: Análise e desenv...,Estágio,Tempo integral,Engenharia e Tecnologia da informação,Desenvolvimento de software,2024-01-11,Desenvolvedor

In [893]:
# Renomeando colunas
df.rename(columns={
    'Title': 'Titulo', 
    'basecard_fulllink_URL': 'Link_vaga', 
    'hiddennestedlink_URL': 'Link_empresa', 
    'hiddennestedlink': 'Empresa', 
    'Location': 'Local', 
    'Date': 'Data_divulgação', 
    'Current_time': 'Data_extracao'
    }, 
    inplace=True
)
df.head(3)

,Titulo,Link_vaga,Link_empresa,Empresa,Local,Data_divulgação,Candidaturas,Descricao,Senioridade,Tipo,Funcao,Setor,Data_extracao,palavra_chave
0,Desenvolvedor(a) Frontend Junior,https://br.linkedin.com/jobs/view/desenvolvedo...,https://br.linkedin.com/company/zenvia-inc?trk...,ZENVIA,"São Paulo, SP",2024-01-10,Mais de 200 candidaturas,O time de Attraction tem a missão de analisar ...,Assistente,Tempo integral,Engenharia e Tecnologia da informação,"Tecnologia, Informação e Internet",2024-01-11,Desenvolvedor
1,Desenvolvedor DataViz Jr - Hibrido - Faria Lim...,https://br.linkedin.com/jobs/view/desenvolvedo...,https://br.linkedin.com/company/iterative-?trk...,Iterative;,"São Paulo, SP",2023-12-27,Seja um dos 25 primeiros a se candidatar,Data Viz Jr.\nResponsabilidades\nAtuar como su...,Pleno-sênior,Tempo integral,Engenharia e Tecnologia da informação,Segurança de redes e computadores,2024-01-11,Desenvolvedor
2,Estágio - Desenvolvedor(a) Java,https://br.linkedin.com/jobs/view/est%C3%A1gio...,https://br.linkedin.com/company/meisters-solut...,Meisters Solutions,"Curitiba, PR",2024-01-08,NaN,Nível: Estagiário\nCursos de: Análise e desenv...,Estágio,Tempo integral,Engenharia e Tecnologia da informação,Desenvolvimento de software,2024-01-11,Desenvolvedor

### Limpando campo de número de candidaturas

In [894]:
# Identificando valores únicos da coluna Candidaturas
df['Candidaturas'].unique()

array(['Mais de 200 candidaturas',
       'Seja um dos 25 primeiros a se candidatar', nan, '40 candidaturas',
       '38 candidaturas', '31 candidaturas', '169 candidaturas',
       '109 candidaturas', '27 candidaturas', '144 candidaturas',
       '30 candidaturas', '94 candidaturas', '110 candidaturas',
       '117 candidaturas', '125 candidaturas', '119 candidaturas',
       '74 candidaturas', '156 candidaturas', '57 candidaturas',
       '97 candidaturas', '46 candidaturas', '133 candidaturas',
       '147 candidaturas', '56 candidaturas', '174 candidaturas',
       '87 candidaturas', '36 candidaturas', '35 candidaturas',
       '142 candidaturas', '65 candidaturas', '71 candidaturas',
       '92 candidaturas', '79 candidaturas', '108 candidaturas',
       '180 candidaturas', '28 candidaturas', '29 candidaturas',
       '93 candidaturas', '26 candidaturas', '102 candidaturas',
       '76 candidaturas', '195 candidaturas', '151 candidaturas',
       '32 candidaturas', '171 candidaturas', '118 candidaturas',
       '101 candidaturas', '54 candidaturas', '78 candidaturas',
       '48 candidaturas', '90 candidaturas', '34 candidaturas',
       '185 candidaturas', '53 candidaturas', '42 candidaturas',
       '69 candidaturas', '168 candidaturas', '50 candidaturas',
       '39 candidaturas', '145 candidaturas', '66 candidaturas',
       '175 candidaturas', '161 candidaturas', '62 candidaturas',
       '183 candidaturas', '80 candidaturas', '190 candidaturas',
       '25 candidaturas', '132 candidaturas', '112 candidaturas',
       '58 candidaturas', '91 candidaturas', '124 candidaturas',
       '140 candidaturas', '173 candidaturas', '139 candidaturas',
       '113 candidaturas', '157 candidaturas', '60 candidaturas',
       '67 candidaturas', '167 candidaturas', '70 candidaturas',
       '130 candidaturas', '170 candidaturas', '192 candidaturas',
       '55 candidaturas', '146 candidaturas', '106 candidaturas',
       '88 candidaturas', '160 candidaturas', '44 candidaturas',
       '86 candidaturas', '59 candidaturas', '197 candidaturas',
       '121 candidaturas', '61 candidaturas', '33 candidaturas',
       '52 candidaturas', '135 candidaturas', '141 candidaturas',
       '49 candidaturas', '37 candidaturas', '138 candidaturas',
       '129 candidaturas', '81 candidaturas', '68 candidaturas',
       '72 candidaturas', '116 candidaturas', '188 candidaturas',
       '134 candidaturas', '103 candidaturas', '73 candidaturas',
       '41 candidaturas', '75 candidaturas', '181 candidaturas',
       '45 candidaturas', '163 candidaturas', '154 candidaturas',
       '43 candidaturas', '164 candidaturas', '82 candidaturas',
       '137 candidaturas', '196 candidaturas', '158 candidaturas',
       '120 candidaturas', '200 candidaturas', '114 candidaturas',
       '166 candidaturas', '115 candidaturas', '84 candidaturas',
       '198 candidaturas', '159 candidaturas', '162 candidaturas',
       '150 candidaturas', '98 candidaturas', '105 candidaturas',
       '149 candidaturas', '104 candidaturas', '165 candidaturas',
       '153 candidaturas', '131 candidaturas', '189 candidaturas',
       '63 candidaturas', '83 candidaturas', '191 candidaturas',
       '47 candidaturas', '100 candidaturas', '148 candidaturas',
       '127 candidaturas', '182 candidaturas', '143 candidaturas',
       '89 candidaturas', '95 candidaturas', '123 candidaturas',
       '126 candidaturas', '51 candidaturas', '152 candidaturas',
       '64 candidaturas', '77 candidaturas', '193 candidaturas',
       '136 candidaturas', '172 candidaturas', '122 candidaturas',
       '96 candidaturas', '85 candidaturas', '155 candidaturas',
       '187 candidaturas', '128 candidaturas', '111 candidaturas',
       '107 candidaturas', '194 candidaturas', '179 candidaturas',
       '178 candidaturas'], dtype=object)

In [895]:
# Tratando a coluna 'Candidaturas'

# Convertendo para string para aplicar operações de texto
df['Candidaturas'] = df['Candidaturas'].astype(str)

# Substituindo textos por valores numéricos
df['Candidaturas'] = df['Candidaturas'].str.replace(' candidaturas', '', regex=False)
df['Candidaturas'] = df['Candidaturas'].str.replace('Seja um dos 25 primeiros a se candidatar', '25', regex=False)
df['Candidaturas'] = df['Candidaturas'].str.replace('Mais de 200', '200', regex=False)

# Convertendo para tipo numérico, com 'coerce' para transformar erros em NaN
df['Candidaturas'] = pd.to_numeric(df['Candidaturas'], errors='coerce')

# Preenchendo valores NaN (resultantes de erros na conversão) com 0 e convertendo para inteiro
df['Candidaturas'] = df['Candidaturas'].fillna(0).astype(int)
print("Coluna 'Candidaturas' após tratamento:")
print(df['Candidaturas'].head())
print(df['Candidaturas'].dtype)

Coluna 'Candidaturas' após tratamento:
0    200
1     25
2      0
3    200
4    200
Name: Candidaturas, dtype: int32
int32

### Tratando duplicatas

In [896]:
# Removendo linhas duplicadas com base na coluna 'Link_vaga'
df.drop_duplicates(subset=['Link_vaga'], inplace=True)
# Verificando o tamanho do DataFrame após remoção de duplicatas
print(f'Tamanho do dataset após remoção de duplicatas: {df.shape[0]} linhas e {df.shape[1]} colunas')

# Verificando valores nulos após remoção de duplicatas
print('Valores nulos após remoção de duplicatas:')
print(df.isnull().sum())

Tamanho do dataset após remoção de duplicatas: 8533 linhas e 14 colunas
Valores nulos após remoção de duplicatas:
Titulo                0
Link_vaga             0
Link_empresa          0
Empresa               0
Local                 0
Data_divulgação       0
Candidaturas          0
Descricao           789
Senioridade         551
Tipo               7969
Funcao              543
Setor               544
Data_extracao         1
palavra_chave         1
dtype: int64

### Limpando informações de localização (cidade e Estado)

In [897]:
# Separando a coluna 'Local' em 'Cidade' e 'Estado'
# Utilizando regex para extrair a cidade e o estado, considerando diferentes formatos
df[["Cidade", "Estado"]] = df["Local"].str.split(", ", n=1, expand=True)
# Removendo a coluna original 'Localizacao'
df.drop(columns=["Local"], inplace=True, errors='ignore')
# Exibindo as primeiras linhas do DataFrame após a separação    
print("DataFrame após separação de Cidade e Estado:")
print(df[["Cidade", "Estado"]].head())

DataFrame após separação de Cidade e Estado:
             Cidade Estado
0         São Paulo     SP
1         São Paulo     SP
2          Curitiba     PR
3    Belo Horizonte     MG
4  Goiânia e Região   None

In [898]:
# Verificando nomes de cidades únicas para padronização
print("Cidades únicas antes da padronização:")
df['Cidade'].unique()

Cidades únicas antes da padronização:

array(['São Paulo', 'Curitiba', 'Belo Horizonte', 'Goiânia e Região',
       'Brasília', 'Palhoça', 'São Leopoldo', 'Luziânia',
       'Santa Catarina', 'Joinville', 'Porto Alegre',
       'Santana de Parnaíba', 'São Paulo e Região', 'Cuiabá',
       'Rio de Janeiro', 'Manaus e Região', 'Recife', 'São Carlos',
       'Aracaju', 'Londrina', 'Agudos', 'Barueri', 'Brasil', 'Medianeira',
       'Olímpia', 'Goiânia', 'Pindamonhangaba', 'Distrito Federal',
       'Ituiutaba', 'Timbó', 'Ortigueira', 'Rio Verde', 'Lajeado',
       'Guarulhos', 'Nova Lima', 'Arroio do Meio', 'Brazil',
       'Federal District', 'Presidente Prudente', 'São Caetano do Sul',
       'Rio do Sul', 'Barro Preto', 'Maringá', 'Greater São Paulo Area',
       'Duque de Caxias', 'Contagem', 'Cocal do Sul', 'Greater Manaus',
       'Porto', 'Santa Maria', 'Porto Velho', 'Campinas', 'Fortaleza',
       'Várzea Grande', 'Florianópolis', 'Chapecó', 'Rio Grande',
       'São Bernardo do Campo', 'Salto', 'Novo Hamburgo',
       'Greater Fortaleza', 'Niterói', 'Ribeirão Preto', 'Sertãozinho',
       'Manaus', 'Rondon', 'Vitória', 'Uberaba', 'Mauá', 'Uberlândia',
       'Greater Goiania', 'São José dos Campos', 'Ipatinga', 'Indaiatuba',
       'Tietê', 'Sorocaba', 'Marília', 'Taquaritinga', 'Teresópolis',
       'Catarina', 'Vila Velha', 'Montes Claros', 'Vitoria',
       'Jaraguá do Sul', 'Greater Cuiaba', 'Santos', 'Taboão da Serra',
       'Joaçaba', 'Barra Velha', 'Greater Recife', 'Santo André',
       'João Pessoa', 'Caxias do Sul', 'Cachoeirinha', 'Greater Curitiba',
       'Mossoró', 'Juiz de Fora', 'Paraguaçu Paulista', 'Betim', 'Bauru',
       'Valinhos', 'Itajaí', 'Jaboticabal', 'Eunápolis',
       'Franco da Rocha', 'Maceió', 'Miraí', 'Taubaté', 'Salvador',
       'Osasco', 'Embu das Artes', 'Tapejara', 'Extrema', 'Palotina',
       'Rancharia', 'Gravataí', 'Greater Rio de Janeiro', 'Campo Grande',
       'Greater Porto Alegre', 'Greater Campinas', 'Piracicaba',
       'Petrópolis', 'Eldorado do Sul', 'Greater Florianopolis', 'Guaíba',
       'Blumenau', 'Pouso Alegre', 'Rio das Ostras', 'Belém', 'Serra',
       'Pato Branco', 'Greater Belo Horizonte', 'Paulínia', 'Camaçari',
       'Imbituba', 'Lauro de Freitas', 'Patos de Minas',
       'Juazeiro do Norte', 'Pacaembu', 'Paulo Frontin', 'Suzano',
       'Rio Branco', 'Mogi Mirim', 'Pimenta Bueno',
       'São Gonçalo do Amarante', 'Aquidauana', 'Minas Gerais', 'Lorena',
       'Campo Largo', 'São José', 'Natal', 'Atibaia', 'Montenegro',
       'Parauapebas', 'Dois Irmãos', 'São Gonçalo', 'Mallet', 'Rio Claro',
       'Itirapina', 'Pinheiro', 'Park Way', 'Picos', 'Imperatriz',
       'Porto Franco', 'Mogi das Cruzes', 'Nova Maringá', 'Paraná',
       'Ribas do Rio Pardo', 'Macaé', 'Lagoa Santa', 'Umuarama',
       'Itabira', 'Deodápolis', 'Palmas', 'São José dos Pinhais',
       'Limeira', 'Aparecida de Goiânia', 'Jundiaí', 'Paracatu',
       'Santa Rita', 'Hortolândia', 'Alvorada', 'Salto de Pirapora',
       'Cotia', 'Ferraz de Vasconcelos', 'Itapevi', 'Cajamar', 'Canoas',
       'São José do Rio Preto', 'Divinópolis', 'Campos do Jordão',
       'Caçador', 'Retiro', 'Vazante', 'Jandaia do Sul', 'Tauá',
       'Campos dos Goytacazes', 'Agrolândia', 'Ribeirão Pires', 'Caucaia',
       'Araucária', 'Alto do Rodrigues', 'Concórdia', 'Criciúma',
       'São Luís', 'Caçapava', 'Belo Monte', 'Laguna', 'Aparecida',
       'Brusque', 'Campo Bom', 'Luís Eduardo Magalhães',
       'Greater Salvador', 'Jacareí', 'Içara', 'Santo Cristo', 'Assis',
       'Canela', 'Paragominas', 'Sumaré', 'Bandeirantes', 'Cascavel',
       'Pinhais', 'Ivoti', 'Balneário Camboriú', 'Porto Belo', 'Resende',
       'Anápolis', 'Sete Lagoas', 'Greater Londrina', 'Dourados',
       'Greater Ribeirão Preto', 'Canas', 'Viamão', 'Portão',
       'Bragança Paulista', 'Horizonte', 'Franca', 'Capão da Canoa',
       'Serafina Corrêa', 'Passo Fundo', 'Senador Canedo',
       'Greater Natal', 'Monte Belo', 'Barra Funda', 'Toledo', 'Gaspar',
       'Teresina', 'Tubarão', 'Almirante Tamandaré', 'Pelotas', 'Lavras',
       'Itumbiara', 'Campo Verde', 'Cataguases', 'Maricá', 'Gramado',
       'Jaru', 'EMEA', 'Ponta Grossa', 'Regente Feijó', 'Araraquara',
       'Santarém', 'Nova Iguaçu', 'Ijuí', 'Goiás',
       'São Gabriel da Cachoeira', 'Itapema', 'Bebedouro', 'Colombo',
       'Itu', 'Paranaguá', 'Itápolis', 'Greater Brasilia', 'Cambé',
       'Olinda', 'Rolândia', 'Foz do Iguaçu', 'Jaboatão dos Guararapes',
       'Paulista', 'Ibiporã', 'Conceição do Mato Dentro', 'Campo Mourão',
       'Moema', 'Santo Antônio de Posse', 'Rondonópolis', 'Schroeder',
       'Três Lagoas', 'Balneário Piçarras', 'Muriaé', 'São Mateus',
       'Varginha', 'Gurupi', 'Caruaru', 'Nova Odessa',
       'Frederico Westphalen', 'Araxá', 'Eusébio', 'Greater Belem',
       'Ceará', 'Porto Seguro', 'Ceilândia', 'Massaranduba',
       'Simões Filho', 'Cristalina', 'Avaré', 'Guaramirim', 'Penha',
       'Mogi Guaçu', 'Saúde', 'Conselheiro Lafaiete',
       'Salinas da Margarida', 'Americana', 'Maracanaú', 'Pilar do Sul',
       'Brumado', 'Carapicuíba', 'Pederneiras', 'Lençóis Paulista',
       'Botucatu', 'Goiana', 'Jandira', 'Cabo de Santo Agostinho',
       'Juruti', 'Araras', 'Macau', 'Ipojuca', 'Rosário do Catete',
       'Itagibá', 'Sinop', 'Rio Largo', 'Volta Redonda', 'Maracaju',
       'Garuva', 'Nossa Senhora do Socorro', 'São Cristóvão', 'Itabaiana',
       'Estância', 'Esteio', 'Boituva', 'Guararema', 'Farroupilha',
       'Itaúna', 'Guaporé', 'Erechim', 'Poços de Caldas', 'Marapoama',
       'Diadema', 'Conde', 'Aracruz', 'Campo Limpo Paulista', 'Oriximiná',
       'Cachoeiras de Macacu', 'Louveira', 'Parnamirim', 'Vila Madalena',
       'Leme', 'Petrolina', 'São Mateus do Sul', 'Crato', 'Caxias',
       'Candelária', 'Gavião Peixoto', 'Várzea Paulista', 'Pauliceia',
       'Itaquaquecetuba', 'Caieiras', 'Coronel Fabriciano',
       'Sapucaia do Sul', 'São Joaquim de Bicas', 'Bento Gonçalves',
       'Navegantes'], dtype=object)

In [899]:
# Removendo "Greater " e " e Região" e " Area" e " Metropolitan Area" da coluna 'Cidade'
df['Cidade'] = df['Cidade'].str.replace(r'Greater | e Região| Area| Metropolitan Area', '', regex=True)

In [900]:
# importando dados do arquivo 'cidades_estados_brasil.csv'
cidades_estados = pd.read_csv('cidades_estados_brasil.csv')
# Verificando as primeiras linhas do DataFrame
print("Primeiras linhas do DataFrame de cidades e estados:")
print(cidades_estados.head())

Primeiras linhas do DataFrame de cidades e estados:
                  Cidade Estado
0  Alta Floresta D'oeste     RO
1              Ariquemes     RO
2                 Cabixi     RO
3                 Cacoal     RO
4             Cerejeiras     RO

In [901]:
# Preenchendo os estados em branco com base nas cidades de acordo com o arquivo 'cidades_estados_brasil.csv'
def preencher_estado(row):
    if pd.isnull(row['Estado']):
        cidade = row['Cidade']
        estado = cidades_estados[cidades_estados['Cidade'] == cidade]['Estado'].values
        if estado.size > 0:
            return estado[0]
    return row['Estado']
df['Estado'] = df.apply(preencher_estado, axis=1)
# Verificando se ainda há valores nulos na coluna 'Estado'
print('Valores nulos na coluna Estado após preenchimento:')
print(df['Estado'].isnull().sum())

Valores nulos na coluna Estado após preenchimento:
1011

In [902]:
# Verificando Cidades sem estado preenchido
print("Cidades sem estado preenchido:")
print(df[df['Estado'].isnull()]['Cidade'].unique())

Cidades sem estado preenchido:
['Brasil' 'Brazil' 'Goiania' 'Cuiaba' 'Florianopolis' 'EMEA' 'Brasilia'
 'Belem']

In [903]:
# Corrigindo nomes de cidades
def corrigir_cidade(cidade):
    if cidade == 'Brazil':
        return 'Não especificado'
    elif cidade == 'Brasil':
        return 'Não especificado'
    elif cidade == 'Goiania':
        return 'Goiânia'
    elif cidade == 'Cuiaba':
        return 'Cuiabá'
    elif cidade == 'Florianopolis':
        return 'Florianópolis'
    elif cidade == 'EMEA':
        return 'Não especificado'
    elif cidade == 'Brasilia':
        return 'Brasília'
    elif cidade == 'Belem':
        return 'Belém'
    else:
        return cidade
df['Cidade'] = df['Cidade'].apply(corrigir_cidade)

### Identificando valores únicos (categorias) de todos os campos

In [904]:
# Identificando valores únicos da coluna Senioridade
df['Senioridade'].unique()

array(['Assistente', 'Pleno-sênior', 'Estágio', 'Júnior', nan],
      dtype=object)

In [905]:
# Identificando valores únicos da coluna Tipo
df['Tipo'].unique()

array(['Tempo integral', 'Contrato', nan, 'Não aplicável', 'Meio período',
       'Outro', 'Voluntário', 'Temporário'], dtype=object)

In [906]:
# Identificando valores únicos da coluna Setor
df['Setor'].unique()

array(['Tecnologia, Informação e Internet',
       'Segurança de redes e computadores', 'Desenvolvimento de software',
       'Publicidade e propaganda',
       'Atividades dos serviços de tecnologia da informação',
       'Produção de mídia', 'Publicação na Internet',
       'Atividades de contabilidade',
       'Fornecimento e gestão de recursos humanos', nan,
       'Serviços ambientais',
       'Atividades profissionais, científicas e técnicas',
       'Pesquisa e desenvolvimento cientifico',
       'Obras de infra-estrutura',
       'Administração, planejamento, regulamentação e fiscalização de transportes',
       'Suprimentos e equipamentos comerciais',
       'Transporte, armazenagem e correio', 'Comércio varejista',
       'Fundos de seguro e benefícios para funcionários',
       'Planejamento, assessoramento e organização de viagens',
       'Serviços de gestão estratégica',
       'Transporte, armazenagem e correio e Transporte rodoviário de carga',
       'Atividades de serviços financeiros',
       'Geração de energia renovável',
       'Atividades de consultoria em gestão empresarial',
       'Mercados de capital, Desenvolvimento de software e Atividades de serviços financeiros',
       'Tecnologia da informação e serviços',
       'Mercados de capital e Desenvolvimento de software',
       'Tecnologia, Informação e Mídia',
       'Recrutamento e seleção de pessoal',
       'Artes, cultura, esporte e recreação',
       'Saúde humana e serviços sociais',
       'Fabricação de veículos automotores, reboques e carrocerias',
       'Serviços de informação',
       'Serviços de dados de tecnologia da informação, Desenvolvimento de software e Operações e manutenção de sistemas de TI',
       'Atividades dos serviços de tecnologia da informação, Tecnologia, Informação e Mídia e Serviços de projeto em tecnologia da informação',
       'Fabricação de cosméticos, produtos de perfumaria e de higiene pessoal',
       'Bancos', 'Atividades de serviços pessoais', 'Serviços de design',
       'Agricultura', 'Sociedades de fomento mercantil - factoring',
       'Assessoria em relações públicas e comunicação',
       'Produtos de computação em rede', 'Atividades de apoio à educação',
       'Atividades dos serviços de tecnologia da informação, Desenvolvimento de software e Operações e manutenção de sistemas de TI',
       'Serviços combinados para apoio a edifícios',
       'Ensino eletrônico, Atividades de apoio à educação e Educação',
       'Treinamento e suporte em tecnologia da informação',
       'Mercados de capital',
       'Infraestrutura e análise de dados e Desenvolvimento e licenciamento de software customizáveis',
       'Fabricação de equipamentos de informática, produtos eletrônicos e ópticos',
       'Administração pública, defesa e seguridade social',
       'Atividades dos serviços de tecnologia da informação e Recrutamento e seleção de pessoal',
       'Recursos humanos',
       'Atividades dos serviços de tecnologia da informação, Serviços de informação e Atividades de serviços financeiros',
       'Atividades de bem-estar e condicionamento físico',
       'Atividades dos serviços de tecnologia da informação, Telecomunicações e Operações e manutenção de sistemas de TI',
       'Atividades de vigilância, segurança e investigação',
       'Educação superior', 'Fabricação de máquinas de automação',
       'Serviços de alimentação e bebidas',
       'Fabricação de cosméticos, produtos de perfumaria e de higiene pessoal, Comércio varejista e Comércio varejista de produtos farmacêuticos, perfumaria e cosméticos',
       'Seguros e previdência complementar', 'Telecomunicações',
       'Obras de infra-estrutura para energia elétrica, telecomunicações, água, esgoto e transporte por dutos',
       'Infraestrutura e análise de dados e Gestão de investimentos em aplicações financeiras',
       'Atividades de apoio à gestão de saúde e Seguros e previdência complementar',
       'Bancos, Atividades de serviços financeiros e Bancos de investimento',
       'Holdings de instituições financeiras e não-financeiras',
       'Alimentos e bebidas', 'Serviços administrativos e complementares',
       'Infraestrutura e análise de dados',
       'Atividades de organizações associativas profissionais',
       'Extração de petróleo e gás natural',
       'Hospitais e atividades de atenção à saúde humana',
       'Transporte aéreo', 'Educação',
       'Serviços de eletricidade, gás, água e esgoto',
       'Fabricação de produtos farmoquímicos e farmacêuticos',
       'Atividades dos serviços de tecnologia da informação, Transporte, armazenagem e correio e Comércio varejista de mercadorias em geral, com predominância de produtos alimentícios',
       'Atividades de rádio e de televisão',
       'Comércio varejista de mercadorias em geral, com predominância de produtos alimentícios',
       'Atividades imobiliárias', 'Atividades esportivas para audiências',
       'Transporte, armazenagem e correio e Tecnologia, Informação e Mídia',
       'Fabricação de produtos alimentícios e bebidas e Pesquisa biotecnológica',
       'Gestão de investimentos em aplicações financeiras',
       'Publicação de jornais', 'Papel e produtos florestais',
       'Produtos de software de computação móvel',
       'Fabricação de máquinas, aparelhos e materiais elétricos',
       'Jogos para computador',
       'Atividades dos serviços de tecnologia da informação, Bancos de investimento e Serviços de projeto em tecnologia da informação',
       'Atividades dos serviços de tecnologia da informação e Desenvolvimento de software',
       'Pesquisas de mercado e de opinião pública',
       'Indústrias de transformação',
       'Consultoria de terceirização e offshoring',
       'Atividades dos serviços de tecnologia da informação, Comércio varejista e Comércio varejista de produtos farmacêuticos, perfumaria e cosméticos',
       'Serviços de assistência social sem alojamento', 'Mineração',
       'Atividades dos serviços de tecnologia da informação, Atividades jurídicas e Atividades de serviços financeiros',
       'Relações exteriores',
       'Atividades dos serviços de tecnologia da informação, Seguros e previdência complementar e Atividades de consultoria em gestão empresarial',
       'Atividades dos serviços de tecnologia da informação, Desenvolvimento de software e Tecnologia, Informação e Internet',
       'Serviços de projeto em tecnologia da informação',
       'Atividades dos serviços de tecnologia da informação, Desenvolvimento de software e Serviços de gestão estratégica',
       'Metalurgia',
       'Serviços de alimentação e bebidas, Fabricação de produtos alimentícios e bebidas e Indústrias de transformação',
       'Desenvolvimento de software e Desenvolvimento e licenciamento de software customizáveis',
       'Agências e corretoras de seguros e Atividades de serviços financeiros',
       'Atividades dos serviços de tecnologia da informação e Treinamento e suporte em tecnologia da informação',
       'Atividades dos serviços de tecnologia da informação e Serviços de dados de tecnologia da informação',
       'Serviços de dados de tecnologia da informação',
       'Atividades dos serviços de tecnologia da informação e Atividades de serviços financeiros',
       'Atividades dos serviços de tecnologia da informação, Serviços de informação e Desenvolvimento de software',
       'Marketing',
       'Atividades dos serviços de tecnologia da informação, Desenvolvimento de software e Atividades de serviços financeiros',
       'Atividades dos serviços de tecnologia da informação e Plataformas de comercialização na Internet',
       'Fabricação de aeronaves', 'Ensino eletrônico',
       'Comércio varejista de artigos do vestuário e acessórios',
       'Serviços de informação e Tecnologia, Informação e Internet',
       'Tecnologia, Informação e Internet e Fornecimento e gestão de recursos humanos',
       'Fabricação de artefatos esportivos',
       'Atividades dos serviços de tecnologia da informação, Publicidade e propaganda e Mídia de áudio e vídeo on-line',
       'Bancos e Atividades de serviços financeiros',
       'Fabricação de máquinas e equipamentos',
       'Plataformas de comercialização na Internet',
       'Fabricação de instrumentos e materiais para uso médico e odontológico e de artigos ópticos',
       'Fabricação de eletrodomésticos',
       'Comércio atacadista de importação e exportação de bens e commodities',
       'Atividades dos serviços de tecnologia da informação, Fabricação de equipamentos de informática e periféricos e Desenvolvimento de software',
       'Serviços de informação e Artes, cultura, esporte e recreação',
       'Telecomunicações sem fio', 'Comércio por atacado',
       'Comércio atacadista especializado em produtos alimentícios e bebidas',
       'Comércio atacadista de materiais de construção em geral',
       'Atividades dos serviços de tecnologia da informação, Desenvolvimento de software e Telecomunicações',
       'Transporte aquaviário',
       'Armazenamento e atividades auxiliares dos transportes',
       'Bancos, Atividades de serviços financeiros e Sociedades de fomento mercantil - factoring',
       'Publicidade e propaganda, Atividades de rádio e de televisão e Serviços de organização, produção e promoção de eventos',
       'Comércio atacadista de importação e exportação de bens e commodities, Bancos e Seguros e previdência complementar',
       'Desenvolvimento de software, Artes, cultura, esporte e recreação e Jogos para computador',
       'Atividades de vigilância e segurança privada',
       'Atividades dos serviços de tecnologia da informação, Segurança de redes e computadores e Bancos',
       'Fabricação de semicondutores de energia renovável',
       'Desenvolvimento de software, Segurança de redes e computadores e Tecnologia, Informação e Internet',
       'Geração de energia elétrica',
       'Desenvolvimento de software, Segurança de redes e computadores e Desenvolvimento e licenciamento de software customizáveis',
       'Fabricação de veículos ferroviários',
       'Atividades dos serviços de tecnologia da informação e Segurança de redes e computadores',
       'Atividades de assistência prestadas em residências coletivas e particulares',
       'Serviços de informação, Tecnologia, Informação e Mídia e Infraestrutura e análise de dados',
       'Atividades de apoio à educação e Atividades de associações de defesa de direitos sociais',
       'Geração de energia elétrica solar',
       'Associações de poupança e empréstimo',
       'Fabricação de produtos químicos',
       'Fabricação de produtos químicos, Comércio atacadista de importação e exportação de bens e commodities e Comércio atacadista de produtos químicos e relacionados',
       'Serviços de dados de tecnologia da informação, Marketing e Infraestrutura e análise de dados',
       'Atividades fotográficas e similares', 'Educação à distância',
       'Construção',
       'Recrutamento e seleção de pessoal e Fornecimento e gestão de recursos humanos',
       'Serviços de informação e Desenvolvimento de software',
       'Fabricação de equipamentos de energia renovável',
       'Desenvolvimento de software, Desenvolvimento e licenciamento de software customizáveis e Tecnologia, Informação e Mídia',
       'Fabricação de produtos alimentícios e bebidas',
       'Atividades dos serviços de tecnologia da informação, Serviços de dados de tecnologia da informação e Infraestrutura e análise de dados',
       'Marketing e Serviços de dados de tecnologia da informação',
       'Fabricação de açúcar, chocolate e produtos derivados',
       'Produtos alimentícios',
       'Agricultura, pecuária, produção florestal e pesca',
       'Comércio varejista de produtos alimentícios e bebidas',
       'Publicidade e propaganda, Comércio atacadista de eletrodomésticos, produtos elétricos e eletrônicos e Plataformas de comercialização na Internet',
       'Fabricação de máquinas e equipamentos de uso industrial específico',
       'Transporte ferroviário e metroferroviário',
       'Serviços de relações com o governo e Administração pública, defesa e seguridade social',
       'Fabricação de máquinas, aparelhos e materiais elétricos e Telecomunicações',
       'Fabricação de instrumentos e materiais para uso médico e odontológico e de artigos ópticos, Pesquisa biotecnológica e Fabricação de produtos farmoquímicos e farmacêuticos',
       'Hotelaria',
       'Tecnologia, Informação e Mídia e Jogos para computador',
       'Atividades de organizações sem fins lucrativos',
       'Atividades jurídicas',
       'Restaurantes e outros serviços de alimentação e bebidas, Serviços de alimentação e bebidas e Comércio varejista',
       'Treinamento em desenvolvimento profissional',
       'Serviços de alimentação e bebidas e Indústrias de transformação',
       'Transporte/Caminhões/Trens', 'Consultórios médicos',
       'Transporte, armazenagem e correio, Fretes e transporte de encomendas e Armazenamento e atividades auxiliares dos transportes',
       'Serviços de informação e Transporte, armazenagem e correio',
       'Consultoria de operações',
       'Desenvolvimento de software, Tecnologia, Informação e Mídia e Desenvolvimento e licenciamento de software customizáveis',
       'Mídia de áudio e vídeo on-line, Ensino eletrônico e Artes, cultura, esporte e recreação',
       'Atividades dos serviços de tecnologia da informação e Administração pública, defesa e seguridade social',
       'Atividades veterinárias',
       'Recrutamento e seleção de pessoal e Atividades de serviços pessoais',
       'Serviços de design, Desenvolvimento de software e Desenvolvimento e licenciamento de software customizáveis',
       'Fabricação de equipamentos de informática e periféricos',
       'Ensino de estética e cabeleireiro',
       'Serviços de organização, produção e promoção de eventos',
       'Atividades dos serviços de tecnologia da informação, Mercados de capital e Design gráfico',
       'Serviços de relações com o governo, Mineração e Consultoria de terceirização e offshoring',
       'Design gráfico', 'Roupas e moda',
       'Atividades dos serviços de tecnologia da informação, Comércio varejista de artigos do vestuário e acessórios e Comércio varejista',
       'Atividades artísticas, criativas e de espetáculos',
       'Comércio varejista de produtos farmacêuticos, perfumaria e cosméticos',
       'Atividades dos serviços de tecnologia da informação, Publicidade e propaganda e Desenvolvimento de software',
       'Atividades dos serviços de tecnologia da informação e Serviços de projeto em tecnologia da informação',
       'Design', 'Conteúdo sobre empresas e negócios',
       'Transporte, armazenagem e correio, Comércio atacadista de medicamentos e drogas de uso humano e Transporte rodoviário de carga',
       'Ensino de secretariado',
       'Serviços de informação e Tecnologia, Informação e Mídia',
       'Publicidade e propaganda, Pesquisas de mercado e de opinião pública e Pesquisa e desenvolvimento cientifico',
       'Administração de serviços de eletricidade, gás, água, esgoto e comunicação',
       'Bancos de investimento',
       'Atividades dos serviços de tecnologia da informação, Saúde humana e serviços sociais e Serviços de projeto em tecnologia da informação',
       'Entretenimento', 'Desenvolvimento de software e Marketing',
       'Atividades dos serviços de tecnologia da informação, Serviços de informação e Serviços de engenharia',
       'Atividades dos serviços de tecnologia da informação, Telecomunicações e Segurança e ordem pública',
       'Desenvolvimento de software, Tecnologia, Informação e Mídia e Operações e manutenção de sistemas de TI',
       'Produtos de software integrado', 'Transporte rodoviário de carga',
       'Desenvolvimento de software e Tecnologia, Informação e Internet',
       'Serviços de informação e Segurança de redes e computadores',
       'Desenvolvimento de software e Tecnologia, Informação e Mídia',
       'Atividades dos serviços de tecnologia da informação, Mercados de capital e Atividades de serviços financeiros',
       'Fabricação de produtos têxteis',
       'Atividades dos serviços de tecnologia da informação, Desenvolvimento de software e Planejamento, assessoramento e organização de viagens',
       'Comércio atacadista de resíduos e sucatas',
       'Comércio varejista e Comércio varejista de jóias e relógios',
       'Comércio varejista especializado de equipamentos e suprimentos de informática',
       'Atividades dos serviços de tecnologia da informação, Treinamento e suporte em tecnologia da informação e Serviços de dados de tecnologia da informação',
       'Recursos renováveis e meio ambiente',
       'Atividades de organizações religiosas',
       'Terceirização e offshoring',
       'Seguros e previdência complementar e Tecnologia, Informação e Mídia',
       'Comércio varejista de produtos farmacêuticos',
       'Tecnologia, Informação e Internet e Atividades de serviços financeiros',
       'Atividades dos serviços de tecnologia da informação e Comércio varejista',
       'Atividades dos serviços de tecnologia da informação, Teste e avaliação de tecnologia da informação e Desenvolvimento de software',
       'Obras de fundações',
       'Atividades dos serviços de tecnologia da informação e Consultoria de terceirização e offshoring',
       'Desenvolvimento e licenciamento de software customizáveis',
       'Construção de rodovias, ruas e pontes',
       'Fabricação de produtos de borracha',
       'Mídia de áudio e vídeo on-line e Tecnologia, Informação e Internet',
       'Atividades dos serviços de tecnologia da informação e Fornecimento e gestão de recursos humanos',
       'Justiça', 'Serviços de engenharia',
       'Plataformas de comercialização na Internet, Bancos e Atividades de serviços financeiros',
       'Desenvolvimento de software e Fabricação de equipamentos de informática, produtos eletrônicos e ópticos',
       'Serviços de escritório e apoio administrativo',
       'Atividades dos serviços de tecnologia da informação e Marketing',
       'Tecnologia, Informação e Mídia e Serviços de projeto em tecnologia da informação',
       'Plataformas de comercialização na Internet e Tecnologia, Informação e Mídia',
       'Fabricação de defensivos agrícolas, adubos e fertilizantes',
       'Fabricação de produtos de material plástico',
       'Atividades dos serviços de tecnologia da informação e Tecnologia, Informação e Internet',
       'Desenvolvimento de software, Fornecimento e gestão de recursos humanos e Atividades de serviços financeiros',
       'Serviços de dados de tecnologia da informação, Comércio varejista e Hospitais e atividades de atenção à saúde humana',
       'Transporte, armazenagem e correio e Plataformas de comercialização na Internet',
       'Transporte, armazenagem e correio e Comércio atacadista de medicamentos e drogas de uso humano',
       'Serviços de informação, Desenvolvimento de software e Tecnologia, Informação e Mídia',
       'Pesquisa e desenvolvimento cientifico e Educação',
       'Desenvolvimento de software e Operações e manutenção de sistemas de TI',
       'Serviços de dados de tecnologia da informação e Infraestrutura e análise de dados',
       'Fabricação de máquinas e equipamentos de uso industrial específico e Mineração',
       'Publicação de livros e periódicos',
       'Comércio varejista de jóias e relógios',
       'Fabricação de produtos alimentícios e bebidas e Sociedades de fomento mercantil - factoring',
       'Fabricação de semicondutores de energia renovável e Extração de petróleo e gás natural',
       'Atividades dos serviços de tecnologia da informação, Teste e avaliação de tecnologia da informação e Infraestrutura e análise de dados',
       'Atividades dos serviços de tecnologia da informação, Publicação de livros e periódicos e Ensino eletrônico',
       'Tradução, interpretação e similares',

In [907]:
# Identificando valores únicos da coluna Funcao
df['Funcao'].unique()

array(['Engenharia e Tecnologia da informação',
       'Tecnologia da informação', nan, 'Administração', 'Outro',
       'Gerenciamento e Manufatura',
       'Desenvolvimento de negócios e Vendas',
       'Tecnologia da informação e Engenharia',
       'Desenvolvimento de negócios e Estratégia/Planejamento',
       'Analista', 'Tecnologia da informação, Analista e Engenharia',
       'Engenharia, Tecnologia da informação e Gestão de projetos',
       'Engenharia, Tecnologia da informação e Consultoria',
       'Recursos humanos', 'Educação e Treinamento', 'Engenharia',
       'Analista, Desenvolvimento de negócios e Tecnologia da informação',
       'Atendimento ao Cliente, Design e Engenharia',
       'Desenvolvimento de negócios',
       'Consultoria, Tecnologia da informação e Atendimento ao Cliente',
       'Design e Arte/Criação',
       'Outro, Tecnologia da informação e Gerenciamento',
       'Analista e Tecnologia da informação', 'Financeiro e Vendas',
       'Tecnologia da informação e Contabilidade/Auditoria',
       'Gestão de projetos e Tecnologia da informação',
       'Vendas e Gerenciamento', 'Vendas e Desenvolvimento de negócios',
       'Gestão de produtos e Marketing',
       'Gestão de projetos, Negócios em geral e Gerenciamento',
       'Educação', 'Tecnologia da informação e Vendas',
       'Provedor de assistência médica', 'Vendas e Analista',
       'Administração e Tecnologia da informação',
       'Administração, Financeiro e Pesquisa',
       'Contabilidade/Auditoria e Administração',
       'Estratégia/Planejamento e Consultoria',
       'Analista e Estratégia/Planejamento', 'Marketing',
       'Pesquisa, Analista e Tecnologia da informação',
       'Consultoria, Tecnologia da informação e Vendas',
       'Estratégia/Planejamento', 'Contabilidade/Auditoria e Financeiro',
       'Compras, Cadeia de suprimentos e Administração',
       'Design, Arte/Criação e Tecnologia da informação',
       'Engenharia, Financeiro e Tecnologia da informação',
       'Treinamento, Gestão de projetos e Administração',
       'Engenharia e Controle de qualidade',
       'Administração, Financeiro e Outro',
       'Atendimento ao Cliente, Outro e Vendas',
       'Provedor de assistência médica, Vendas e Ciências',
       'Marketing, Relações públicas e Composição e revisão de textos',
       'Financeiro', 'Tecnologia da informação e Gestão de projetos',
       'Atendimento ao Cliente, Tecnologia da informação e Outro',
       'Analista, Tecnologia da informação e Outro',
       'Gestão de projetos, Tecnologia da informação e Outro',
       'Tecnologia da informação e Outro',
       'Analista, Tecnologia da informação e Consultoria',
       'Controle de qualidade',
       'Gestão de projetos, Consultoria e Negócios em geral',
       'Tecnologia da informação e Controle de qualidade',
       'Consultoria e Desenvolvimento de negócios', 'Gerenciamento',
       'Vendas, Desenvolvimento de negócios e Estratégia/Planejamento',
       'Outro, Consultoria e Tecnologia da informação',
       'Desenvolvimento de negócios, Tecnologia da informação e Engenharia',
       'Consultoria e Tecnologia da informação', 'Vendas',
       'Outro e Tecnologia da informação',
       'Analista, Tecnologia da informação e Gerenciamento',
       'Financeiro e Tecnologia da informação', 'Atendimento ao Cliente',
       'Marketing e Vendas',
       'Engenharia, Tecnologia da informação e Vendas',
       'Marketing e Estratégia/Planejamento', 'Design',
       'Tecnologia da informação, Manufatura e Gerenciamento',
       'Gestão de projetos, Tecnologia da informação e Gestão de produtos',
       'Compras e Cadeia de suprimentos',
       'Tecnologia da informação e Atendimento ao Cliente',
       'Gestão de projetos, Gerenciamento e Gestão de produtos',
       'Engenharia, Tecnologia da informação e Atendimento ao Cliente',
       'Design e Tecnologia da informação',
       'Vendas, Desenvolvimento de negócios e Atendimento ao Cliente',
       'Engenharia, Tecnologia da informação e Engenharia',
       'Jurídico e Outro', 'Função\nControle de qualidade',
       'Função\nTecnologia da informação',
       'Função\nOutro, Tecnologia da informação e Gerenciamento',
       'Função\nTecnologia da informação e Consultoria',
       'Função\nVendas, Negócios em geral e Atendimento ao Cliente',
       'Função\nJurídico',
       'Função\nEngenharia e Tecnologia da informação',
       'Função\nTecnologia da informação e Estratégia/Planejamento',
       'Função\nDesenvolvimento de negócios e Vendas',
       'Função\nConsultoria', 'Função\nGerenciamento e Manufatura',
       'Função\nConsultoria, Tecnologia da informação e Vendas',
       'Função\nEstratégia/Planejamento, Gestão de projetos e Tecnologia da informação',
       'Função\nGestão de projetos e Tecnologia da informação',
       'Função\nAdministração',
       'Função\nAnalista, Tecnologia da informação e Gerenciamento',
       'Função\nTecnologia da informação e Financeiro',
       'Função\nAnalista, Engenharia e Pesquisa',
       'Função\nContabilidade/Auditoria e Financeiro', 'Função\nOutro',
       'Função\nVendas e Desenvolvimento de negócios',
       'Função\nFinanceiro e Vendas',
       'Função\nConsultoria, Tecnologia da informação e Atendimento ao Cliente',
       'Função\nRecursos humanos', 'Função\nEngenharia',
       'Função\nTecnologia da informação e Engenharia',
       'Analista e Pesquisa', 'Jurídico',
       'Gerenciamento, Manufatura e Desenvolvimento de negócios',
       'Atendimento ao Cliente, Tecnologia da informação e Analista',
       'Desenvolvimento de negócios, Tecnologia da informação e Marketing',
       'Gestão de projetos', 'Relações públicas',
       'Administração, Engenharia e Tecnologia da informação',
       'Consultoria e Gerenciamento',
       'Tecnologia da informação e Consultoria',
       'Tecnologia da informação, Engenharia e Design',
       'Engenharia, Tecnologia da informação e Ciências',
       'Tecnologia da informação, Analista e Estratégia/Planejamento',
       'Consultoria', 'Administração e Marketing',
       'Vendas, Desenvolvimento de negócios e Publicidade',
       'Controle de qualidade, Engenharia e Gestão de projetos',
       'Produção',
       'Engenharia, Controle de qualidade e Gestão de produtos',
       'Administração, Publicidade e Arte/Criação',
       'Administração e Gestão de projetos', 'Distribuição',
       'Estratégia/Planejamento, Arte/Criação e Gestão de projetos',
       'Administração, Engenharia e Outro', 'Contabilidade/Auditoria',
       'Tecnologia da informação, Gestão de produtos e Gestão de projetos',
       'Consultoria, Marketing e Tecnologia da informação',
       'Administração e Analista',
       'Analista, Estratégia/Planejamento e Cadeia de suprimentos',
       'Administração e Contabilidade/Auditoria',
       'Administração, Desenvolvimento de negócios e Atendimento ao Cliente',
       'Desenvolvimento de negócios e Gestão de produtos',
       'Gerenciamento e Gestão de projetos', 'Publicidade',
       'Atendimento ao Cliente e Vendas',
       'Design, Tecnologia da informação e Engenharia',
       'Arte/Criação e Design', 'Arte/Criação, Administração e Design',
       'Tecnologia da informação e Design',
       'Publicidade, Relações públicas e Marketing', 'Design e Marketing',
       'Gestão de projetos, Desenvolvimento de negócios e Tecnologia da informação',
       'Arte/Criação',
       'Arte/Criação, Tecnologia da informação e Engenharia',
       'Publicidade, Arte/Criação e Composição e revisão de textos',
       'Marketing e Publicidade', 'Tecnologia da informação e Marketing',
       'Analista, Arte/Criação e Desenvolvimento de negócios',
       'Gestão de produtos', 'Composição e revisão de textos',
       'Arte/Criação e Marketing',
       'Analista, Administração e Desenvolvimento de negócios',
       'Gestão de produtos, Design e Financeiro',
       'Atendimento ao Cliente, Composição e revisão de textos e Arte/Criação',
       'Arte/Criação, Design e Gestão de produtos',
       'Administração, Arte/Criação e Design',
       'Consultoria, Engenharia e Design',
       'Tecnologia da informação, Analista e Consultoria',
       'Tecnologia da informação, Analista e Desenvolvimento de negócios',
       'Controle de qualidade e Engenharia',
       'Tecnologia da informação, Consultoria e Engenharia',
       'Engenharia, Administração e Tecnologia da informação',
       'Engenharia, Tecnologia da informação e Desenvolvimento de negócios',
       'Design, Engenharia e Tecnologia da informação',
       'Desenvolvimento de negócios e Outro',
       'Consultoria, Tecnologia da informação e Outro', 'Design e Outro',
       'Outro, Tecnologia da informação e Engenharia',
       'Financeiro, Tecnologia da informação e Consultoria',
       'Engenharia, Tecnologia da informação e Design',
       'Contabilidade/Auditoria, Administração e Consultoria',
       'Consultoria, Negócios em geral e Estratégia/Planejamento',
       'Educação e Tecnologia da informação',
       'Tecnologia da informação, Desenvolvimento de negócios e Engenharia',
       'Tecnologia da informação e Negócios em geral',
       'Financeiro, Contabilidade/Auditoria e Consultoria',
       'Marketing, Publicidade e Estratégia/Planejamento',
       'Tecnologia da informação e Analista',
       'Publicidade e Tecnologia da informação',
       'Engenharia, Tecnologia da informação e Estratégia/Planejamento',
       'Administração e Pesquisa',
       'Administração, Gestão de projetos e Tecnologia da informação',
       'Tecnologia da informação, Desenvolvimento de negócios e Estratégia/Planejamento',
       'Cadeia de suprimentos e Tecnologia da informação',
       'Pesquisa e Educação',
       'Gestão de projetos, Gestão de produtos e Tecnologia da informação',
       'Administração e Engenharia',
       'Analista, Engenharia e Tecnologia da informação',
       'Manufatura, Gerenciamento e Outro',
       'Financeiro, Recursos humanos e Tecnologia da informação',
       'Publicidade e Desenvolvimento de negócios',
       'Engenharia, Estratégia/Planejamento e Gestão de projetos',
       'Engenharia e Outro',
       'Tecnologia da informação e Gestão de produtos',
       'Vendas, Gerenciamento e Financeiro',
       'Engenharia, Marketing e Pesquisa',
       'Atendimento ao Cliente e Tecnologia da informação',
       'Tecnologia da informação, Gestão de projetos e Outro',
       'Recursos humanos, Gestão de projetos e Treinamento',
       'Negócios em geral, Gerenciamento e Desenvolvimento de negócios',
       'Administração, Gestão de projetos e Estratégia/Planejamento',
       'Gestão de produtos, Tecnologia da informação e Estratégia/Planejamento',
       'Tecnologia da informação, Contabilidade/Auditoria e Marketing',
       'Tecnologia da informação, Consultoria e Outro',
       'Jurídico e Consultoria', 'Negócios em geral',
       'Tecnologia da informação, Contabilidade/Auditoria e Atendimento ao Cliente',
       'Educação e Vendas', 'Tecnologia da informação, Outro e Analista',
       'Analista e Publicidade', 'Relações públicas e Marketing',
       'Marketing, Publicidade e Outro', 'Marketing e Marketing',
       'Design, Publicidade e Marketing',
       'Analista, Marketing e Publicidade',
       'Estratégia/Planejamento e Publicidade',
       'Tecnologia da informação, Marketing e Composição e revisão de textos',
       'Marketing, Arte/Criação e Outro',
       'Distribuição, Marketing e Relações públicas',
       'Administração, Tecnologia da informação e Marketing',
       'Vendas, Estratégia/Planejamento e Marketing',
       'Estratégia/Planejamento, Analista e Composição e revisão de textos',
       'Marketing e Analista', 'Marketing e Desenvolvimento de negócios',
       'Marketing e Outro', 'Administração e Vendas',
       'Marketing e Relações públicas', 'Negócios em geral e Vendas',
       'Desenvolvimento de negócios, Atendimento ao Cliente e Financeiro',
       'Financeiro, Contabilidade/Auditoria e Administração',
       'Vendas, Marketing e Analista', 'Manufatura',
       'Manufatura e Produção', 'Analista e Engenharia',
       'Administração, Engenharia e Estratégia/Planejamento',
       'Engenharia, Financeiro e Outro', 'Administração e Financeiro',
       'Provedor de assistência médica e Tecnologia da informação',
       'Recursos humanos, Administração e Treinamento',
       'Provedor de assistência médica e Vendas',
       'Tecnologia da informação, Atendimento ao Cliente e Engenharia',
       'Administração e Provedor de assistência médica',
       'Desenvolvimento de negócios, Analista e Outro',
       'Contabilidade/Auditoria, Administração e Financeiro',
       'Gestão de projetos, Tecnologia da informação e Gerenciamento',
       'Tecnologia da informação, Estratégia/Planejamento e Consultoria',
       'Financeiro e Contabilidade/Auditoria',
       'Vendas, Atendimento ao Cliente e Gerenciamento',
       'Tecnologia da informação, Administração e Outro',
       'Distribuição e Cadeia de suprimentos',
       'Administração, Contabilidade/Auditoria e Financeiro',
       'Educação, Engenharia e Outro',
       'Tecnologia da informação e Estratégia/Planejamento',
       'Desenvolvimento de negócios, Engenharia e Tecnologia da informação',
       'Atendimento ao Cliente e Recursos humanos',
       'Financeiro, Analista e Tecnologia da informação',
       'Engenharia, Consultoria e Atendimento ao Cliente',
       'Desenvolvimento de negócios, Tecnologia da informação e Gestão de produtos',
       'Tecnologia da informação, Financeiro e Outro',
       'Administração, Tecnologia da informação e Engenharia',
       'Vendas, Tecnologia da informação e Consultoria',
       'Gerenciamento e Analista', 'Gerenciamento e Financeiro',
       'Tecnologia da informação, Gestão de projetos e Desenvolvimento de negócios',
       'Tecnologia da informação, Engenharia e Desenvolvimento de negócios',
       'Vendas e Gestão de projetos',
       'Atendimento ao Cliente, Consultoria e Vendas',
       'Negócios em geral, Tecnologia da informação e Gestão de projetos',
       'Desenvolvimento de negócios e Gestão de projetos',
       'Tecnologia da informação, Desenvolvimento de negócios e Consultoria',
       'Consultoria e Outro',
       'Analista, Desenvolvimento de negócios e Gestão de projetos',
       'Analista e Outro',
       'Tecnologia da informação, Consultoria e Gestão de projetos',
       'Tecnologia da informação, Analista e Gerenciamento',
       'Vendas, Gestão de projetos e Desenvolvimento de negócios',
       'Vendas, Publicidade e Atendimento ao Cliente',
       'Vendas, Educação e Desenvolvimento de negócios',
       'Recursos humanos, Tecnologia da informação e Outro'], dtype=object)

### Tratando valores nulos

In [908]:
# Tratando valores nulos
# Preenchendo valores nulos em colunas categóricas com 'Não Informado' para evitar problemas em análises futuras
for col in ["Senioridade", "Tipo", "Funcao", "Setor", "Cidade", "Estado", "Categoria", "Sub_Categoria", "nivel", "tipo_loc"]:
    if col in df.columns:
        df[col] = df[col].fillna("Não Informado")

# Removendo linhas onde 'Titulo' ou 'Descricao' são nulos, pois são essenciais para a análise de vagas
df.dropna(subset=["Titulo", "Descricao"], inplace=True)
df.reset_index(drop=True, inplace=True)

In [909]:
# Encontrando colunas com todas as linhas zeradas e eliminá-las

zeros = (df == 0) & (df.applymap(type) == int)
cols = zeros.all()[zeros.all()].index.to_list()
df = df.drop(cols, axis=1)

print("Valores nulos após tratamento:")
print(df.isnull().sum())
# Verificando o tamanho do DataFrame após todos os tratamentos
print(f'Tamanho do dataset após tratamento: {df.shape[0]} linhas e {df.shape[1]} colunas')

Valores nulos após tratamento:
Titulo             0
Link_vaga          0
Link_empresa       0
Empresa            0
Data_divulgação    0
Candidaturas       0
Descricao          0
Senioridade        0
Tipo               0
Funcao             0
Setor              0
Data_extracao      0
palavra_chave      0
Cidade             0
Estado             0
dtype: int64
Tamanho do dataset após tratamento: 7744 linhas e 15 colunas

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\571961212.py:3: FutureWarning:

DataFrame.applymap has been deprecated. Use DataFrame.map instead.

### Identificando habilidades técnicas mencionadas na descrição da vaga

In [910]:
# Padronizando o texto para facilitar a busca por habilidades e categorização
# Convertendo colunas de texto para maiúsculas e removendo caracteres especiais

# Função para limpar mantendo acentos
def limpar_texto(texto):
    texto = str(texto).upper()
    # Permite letras maiúsculas (incluindo acentuadas), números e espaços
    return re.sub(r'[^A-ZÁÉÍÓÚÂÊÎÔÛÃÕÇÀÈÌÒÙ0-9\s]', ' ', texto)

# Aplicando às colunas
df["Descricao"] = df["Descricao"].apply(limpar_texto)
df["Empresa"] = df["Empresa"].apply(limpar_texto)
df["Titulo"] = df["Titulo"].apply(limpar_texto)

df["Senioridade"] = df["Senioridade"].astype(str).str.upper()
df["Tipo"] = df["Tipo"].astype(str).str.upper()
df["Funcao"] = df["Funcao"].astype(str).str.upper()

df.head(3)

,Titulo,Link_vaga,Link_empresa,Empresa,Data_divulgação,Candidaturas,Descricao,Senioridade,Tipo,Funcao,Setor,Data_extracao,palavra_chave,Cidade,Estado
0,DESENVOLVEDOR A FRONTEND JUNIOR,https://br.linkedin.com/jobs/view/desenvolvedo...,https://br.linkedin.com/company/zenvia-inc?trk...,ZENVIA,2024-01-10,200,O TIME DE ATTRACTION TEM A MISSÃO DE ANALISAR ...,ASSISTENTE,TEMPO INTEGRAL,ENGENHARIA E TECNOLOGIA DA INFORMAÇÃO,"Tecnologia, Informação e Internet",2024-01-11,Desenvolvedor,São Paulo,SP
1,DESENVOLVEDOR DATAVIZ JR HIBRIDO FARIA LIM...,https://br.linkedin.com/jobs/view/desenvolvedo...,https://br.linkedin.com/company/iterative-?trk...,ITERATIVE,2023-12-27,25,DATA VIZ JR \nRESPONSABILIDADES\nATUAR COMO SU...,PLENO-SÊNIOR,TEMPO INTEGRAL,ENGENHARIA E TECNOLOGIA DA INFORMAÇÃO,Segurança de redes e computadores,2024-01-11,Desenvolvedor,São Paulo,SP
2,ESTÁGIO DESENVOLVEDOR A JAVA,https://br.linkedin.com/jobs/view/est%C3%A1gio...,https://br.linkedin.com/company/meisters-solut...,MEISTERS SOLUTIONS,2024-01-08,0,NÍVEL ESTAGIÁRIO\nCURSOS DE ANÁLISE E DESENV...,ESTÁGIO,TEMPO INTEGRAL,ENGENHARIA E TECNOLOGIA DA INFORMAÇÃO,Desenvolvimento de software,2024-01-11,Desenvolvedor,Curitiba,PR

In [911]:
# Listando as habilidades técnicas que queremos encontrar
habilidades_tecnicas = [" AGILE ", 
                        " ANDROID ", 
                        " ANGULAR ", 
                        " ANSIBLE ", 
                        " ASP ",  
                        " APACHE ", 
                        " API ", 
                        " AUDIT ", 
                        " AUTOMAÇÃO ", 
                        " AWS ", 
                        " AZURE ", 
                        " BACK ", 
                        " BIG DATA ", 
                        " BOOTSTRAP ", 
                        " C ", 
                        " C# ", 
                        " C++ ", 
                        " CD ", 
                        " CI ", 
                        " CHATBOT ", 
                        " CLOUD ", 
                        " COBIT ", 
                        " COBOL ", 
                        " CRM ", 
                        " CRO ", 
                        " CSS ", 
                        " CX ", 
                        " DEEP LEARNING ", 
                        " DELPHI ", 
                        " DJANGO ", 
                        " DOCKER ", 
                        " EDR ", 
                        " ELIXIR ", 
                        " ENGLISH ", 
                        " ETL ", 
                        " EXCEL ", 
                        " FASTAPI ", 
                        " FIGMA ", 
                        " FIREWALL ", 
                        " FLASK ", 
                        " FLUTTER ", 
                        " FRONT ", 
                        " GIT ", 
                        " GO ", 
                        " CLOUD ", 
                        " GRAPHQL ", 
                        " HACKING ", 
                        " HADOOP ", 
                        " HTML ", 
                        " IA ", 
                        " ILUSTRATOR ", 
                        " INGLÊS ", 
                        " INTELIGÊNCIA ARTIFICIAL ", 
                        " IONIC ", 
                        " IOS ", 
                        " ITIL ", 
                        " JAVA ", 
                        " JAVASCRIPT ", 
                        " JENKINS ", 
                        " JIRA ", 
                        " JQUERY ", 
                        " JSON ", 
                        " KAFKA ", 
                        " KERAS ", 
                        " KOTLIN ", 
                        " KUBERNETES ", 
                        " LARAVEL ", 
                        " LEAN ", 
                        " LINUX ", 
                        " LOOKER ", 
                        " MACHINE LEARNING ", 
                        " MAINFRAME ", 
                        " MICROSSERVIÇOS ", 
                        " MIRO ", 
                        " ML ", 
                        " MONGODB ", 
                        " MVC ", 
                        " MYSQL ", 
                        " NET ", 
                        " NEXT ", 
                        " NIST ", 
                        " NOCODE ", 
                        " NODE ", 
                        " NOSQL ", 
                        " ORACLE ", 
                        " PENTESTING ", 
                        " PHOTOSHOP ", 
                        " PHP ", 
                        " POSTGRESQL ", 
                        " POWER BI ", 
                        " PYTHON ", 
                        " PYTORCH ", 
                        " QA ", 
                        " R ", 
                        " REACT ", 
                        " REDUX ", 
                        " RESTFUL ", 
                        " RPA ", 
                        " RUBY ", 
                        " RUBY ON RAILS ", 
                        " SAAS ", 
                        " SALESFORCE ", 
                        " SCALA ", 
                        " SCRUM ", 
                        " SELENIUM ", 
                        " SIEM ", 
                        " SOC ", 
                        " SPARK ", 
                        " SPRING ", 
                        " SQL ", 
                        " STACK ", 
                        " SWIFT ", 
                        " TABLEAU ", 
                        " TDD ", 
                        " TERRAFORM ", 
                        " TYPESCRIPT ",
                        " TESTE ", 
                        " UI ", 
                        " UNIX ", 
                        " UX ", 
                        " VIRTUALIZATION ", 
                        " VUE ", 
                        " WORDPRESS ", 
                        ]

In [912]:
# Criando colunas para cada habilidade e preenchendo com 0 ou 1
for habilidade in habilidades_tecnicas:
    df[habilidade] = df["Descricao"].apply(lambda x: 1 if re.search(r'\b' + re.escape(habilidade) + r'\b', str(x), flags=re.IGNORECASE) else 0)

# Removendo colunas de habilidades que não apareceram em nenhuma vaga
cols_to_drop = [col for col in habilidades_tecnicas if col in df.columns and df[col].sum() == 0]
df.drop(columns=cols_to_drop, inplace=True, errors="ignore")

print("Colunas de habilidades criadas.")

# Filtra apenas colunas de habilidades (que estão na lista original)
cols_habilidades = [col for col in df.columns if col in habilidades_tecnicas]
print(cols_habilidades[:10])  # Exibe as primeiras 10 colunas de habilidades
print(f"Total de colunas de habilidades restantes: {len(cols_habilidades)}")

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Colunas de habilidades criadas.
[' AGILE ', ' ANDROID ', ' ANGULAR ', ' ANSIBLE ', ' ASP ', ' APACHE ', ' API ', ' AUDIT ', ' AUTOMAÇÃO ', ' AWS ']
Total de colunas de habilidades restantes: 117

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4220944675.py:3: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

### Categorizando vagas de acordo com títulos

In [913]:
# Identificando valores únicos da coluna Titulo
valores_unicos_Titulo = df['Titulo'].unique()
valores_unicos_Titulo

array(['DESENVOLVEDOR A  FRONTEND JUNIOR',
       'DESENVOLVEDOR DATAVIZ JR   HIBRIDO   FARIA LIMA   SP',
       'ESTÁGIO   DESENVOLVEDOR A  JAVA', ...,
       'OPERADOR E PROGRAMADOR DE CENTRO DE USINAGEM   MANDRILHADORA',
       'ANALISTA DE MATERIAIS', 'FRESADOR PROGRAMADOR CNC'], dtype=object)

In [914]:
# Função para categorizar a vaga com base no Título
def categorizar_vaga(titulo):
    titulo = str(titulo).upper()
    if any(keyword in titulo for keyword in ["DESENVOLVEDOR", "SOFTWARE", "DEVELOPER", "PROGRAMADOR", "FRONT", "BACK", "DESENVOLVIMENTO", "PYTHON", "GOLANG", "STACK", "JAVA", "MOBILE", "DESARROLLADOR", "NODE", "REACT", "DEV"]):
        return "DESENVOLVIMENTO"
    elif any(keyword in titulo for keyword in ["NEGÓCIOS", "ANALISTA DE PROJETOS", "CUSTOMER SUCCESS", "OPERAÇÕES", "OPERATIONS", "CRM", "CX", "BUSINESS ANALYST", "SISTEMAS", "ANALISTA FINANCEIRO", "GROWTH", "MELHORIA CONTÍNUA", "ANALISTA DE SISTEMAS", "ANALISTA DE NEGÓCIOS", "LOGÍSTICA", "ERP", "SAP", "ORACLE ERP", "TOTVS", "DYNAMICS"]):
        return "ANALISTAS DE NEGÓCIOS"
    elif any(keyword in titulo for keyword in ["TI", "IT", "ANALISTA DE TECNOLOGIA", "ANALISTA DE GESTÃO DA INFORMAÇÃO", "ANALISTA DE TECNOLOGIA", "ANALISTA DE SISTEMAS", "SYSTEM"]):
        return "ANALISTA DE SISTEMAS"
    elif any(keyword in titulo for keyword in ["DATA", "DADOS", "DBA", "BANCO DE DADOS", "SQL", "ML", "MACHINE LEARNING", "POWER BI", "INTELLIGENCE", "INTELIGÊNCIA", "QUALITATIVE", "DADO", "ANALISTA DE NEGÓCIO", "ANALISTA DE GROWTH", "ESTATÍSTICA", "STATISTICS", "ETL", "INTELIGENCE", "DASHBOARD", "BI ANALYST", "ANALISTA DE BI", "ANALYTICS", "BI ENGINEER", "AI ", "BI ", " IA"]):
        return "DADOS/BI"
    elif any(keyword in titulo for keyword in ["QA", "TESTE", "QUALIDADE", "QUALITY", "TEST"]):
        return "QUALIDADE/TESTES"
    elif any(keyword in titulo for keyword in ["SEGURANÇA", "CYBER", "RISCO", "SECURITY", "FRAUDE"]):
        return "SEGURANÇA DA INFORMAÇÃO"
    elif any(keyword in titulo for keyword in ["CLOUD", "ARQUITETO", "ARCHITECT", "DEVOPS", "TERRAFORM", "ANSIBLE", "INFRAESTRUTURA", "RELIABILITY", "SRE", "INFRA", "INFRASTRUCTURE", "KUBERNET", "DOCKER", "AWS", "AZURE", "GCP", "CICD", "CONTÊINERES", "CONTAINERIZATION", "VIRTUALIZAÇÃO", "KUBERNETES", "ORACLE", "REDES", "NETWORK", "SDN", "ROUTER", "SWITCH", "FIREWALL"]):
        return "CLOUD/DEVOPS/INFRA"
    elif any(keyword in titulo for keyword in ["SUPORTE", "HELP DESK"]):
        return "SUPORTE TÉCNICO"
    elif any(keyword in titulo for keyword in ["UX", "UI", "DESIGNER", "DESIGN", "USER EXPERIENCE", "USER INTERFACE", "PROTOTIPAGEM", "FIGMA", "UX DESIGNER", "UI DESIGNER", "UX/UI", "DESIGNER GRÁFICO", "DESIGNER DE INTERAÇÃO", "DESIGNER DE PRODUTO"]):
       return "DESIGN/UX/UI"
    elif any(keyword in titulo for keyword in ["GERENTE DE PROJETOS", "PO", "PRODUCT OWNER", "GERENTE DE PRODUTO", "GERENTE DE TI", "COORDENADOR", "TECH LEAD", "SCRUM", "PROJECT MANAGER", "AGILE", "PMO", "PRODUCT MANAGER"]):
        return "LIDERANÇA"
    elif any(keyword in titulo for keyword in ["MARKETING", "COMUNICAÇÃO", "SOCIAL MEDIA", "SEO", "SEM", "MÍDIA", "CONTEÚDO"]):
        return "MARKETING/DIGITAL"
    elif any(keyword in titulo for keyword in ["BANCO DE TALENTOS"]):
        return "BANCO DE TALENTOS"
    else:
        return "OUTROS"

df["Categoria"] = df["Titulo"].apply(categorizar_vaga)
print("Vagas categorizadas com base no título.")
print(df[["Titulo", "Categoria"]].head())

Vagas categorizadas com base no título.
                                              Titulo        Categoria
0                   DESENVOLVEDOR A  FRONTEND JUNIOR  DESENVOLVIMENTO
1  DESENVOLVEDOR DATAVIZ JR   HIBRIDO   FARIA LIM...  DESENVOLVIMENTO
2                    ESTÁGIO   DESENVOLVEDOR A  JAVA  DESENVOLVIMENTO
3                         DESENVOLVEDOR FRONT END JR  DESENVOLVIMENTO
4                           DESENVOLVEDOR FULL STACK  DESENVOLVIMENTO

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\2394251050.py:31: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

In [915]:
# Verificando observações por categoria
df['Categoria'].value_counts()

Categoria
DESENVOLVIMENTO            3023
ANALISTA DE SISTEMAS       1549
OUTROS                      816
DADOS/BI                    734
DESIGN/UX/UI                620
ANALISTAS DE NEGÓCIOS       321
LIDERANÇA                   164
CLOUD/DEVOPS/INFRA          160
BANCO DE TALENTOS            83
SEGURANÇA DA INFORMAÇÃO      77
MARKETING/DIGITAL            75
QUALIDADE/TESTES             61
SUPORTE TÉCNICO              61
Name: count, dtype: int64

In [916]:
# Identificando títulos que ainda não foram categorizados
Categoria_outro = df.loc[df['Categoria'] == 'OUTROS', 'Titulo']
Categoria_outro = Categoria_outro.tolist()
random.shuffle(Categoria_outro)
print(Categoria_outro)

['PROJECT MANAGEMENT OFFICER   PAYMENTS HUB', 'BOLSISTA INOVA TALENTOS IEL   CNPQ   BANCO NEXT', 'TRADE FINANCE PROFESSIONALS', 'ESPECIALISTA DE FP A LATAM', 'LÍDER TÉCNICO', 'SDR   PRÉ VENDAS', 'ASSISTENTE DE ATENDIMENTO   AGÊNCIA NOVA MARINGÁ   MT', 'GESTOR A  DE TRÁFEGO', 'CONSULTOR TÉCNICO', 'ESTAGIÁRIO JURÍDICO', 'ANALISTA DE FP A PLENO', 'ESPECIALISTA EM PROCEDIMENTOS INVASIVOS   INJETOR', 'EMPACOTADOR  SÃO PAULO   DARK CONSOLAÇÃO', 'INSTRUTOR RPA DRONE', 'ANALISTA DE GESTÃO DE PESSOAS', 'ASSISTENTE ADMISSIBILIDADE', 'ANALYST  BIOENERGY  BIOFUELS RESEARCH', 'TÉCNICO SENIOR III', 'ANALISTA DE PROGRAMAÇÃO JR', 'ANALISTA DE DEPARTAMENTO PESSOAL SENIOR   CENTRAL BRASIL', 'SR FINANCIAL LINES CLAIMS SPECIALIST', 'DIRETOR A REGIONAL DE DEEP LEARNING  CONSULTORIA TECNOLÓGICA    SÃO PAULO  BRASIL ', 'STAFF GAME ENGINEER', 'GERENTE DE RELACIONAMENTO', 'COMERCIAL   ANALISTA DE MERCADO', 'STAFF CONSULTANT', 'TÉCNICO EM ELETRÔNICA', 'TORNEIRO MECÂNICO', 'ASSISTENTE FINANCEIRO I', 'TECHNICAL ACCOUNT MANAGER   SUCESSO DO CLIENTE', 'ENTREGADOR', 'ANALISTA DE SUSTENTAÇÃO', 'ESTÁGIO   CENTRO DE EXCELÊNCIA', 'ESTAGIÁRIO A    GOIÂNIA   GO', 'APRENDIZ OPERACIONAL   BALCONISTA SAWADE', 'RELACIONAMENTO COM O CLIENTE   JÚNIOR PLENO', 'ESTAGIÁRIO', 'ESTAGIO TECNOLOGIA DE INFORMAÇÃO', 'ASSISTENTE COMERCIAL   INSIDE SALES', 'ANALISTA DE AUTORIZAÇÕES   RIO DE JANEIRO  RJ   1036674', 'BILLING ANALYST', 'GERENTE REGIONAL DE VENDAS   UBERLÂNDIA MG', 'INSTRUTOR DE TREINAMENTO   RPA', 'SENIOR CASH MANAGEMENT ANALYST', 'GESTÃO DE TELECOMUNICAÇÕES', 'ANALISTA DE AUTORIZAÇÕES   RIO DE JANEIRO  RJ   1036674', 'AGENTE DE ATENDIMENTO  CRC ', 'ESTAGIÁRIO', 'CHANNEL SALES MANAGER', 'ANALISTA DE INFORMACOES GERENCIAIS SR', 'ABASTECEDOR', 'ANALISTA SOC JR', 'ANALYST  BIOENERGY  BIOFUELS RESEARCH', 'ASSISTENTE DE PRODUTOS', 'ANALISTA DE PRODUTOS', 'COMPRADOR  SANTO ANDRÉ', 'SENIOR ENGINEER LEAD  SEARCH', 'COMUNICADOR VISUAL OPERACIONAL  VIAMÃO  RS', 'VENDEDOR', 'ESPECIALISTA EM RPA', 'COORDENAÇÃO DE PLANEJAMENTO ESTRATÉGICO', 'ANALISTA DE PERFOMANCE', 'MENTOR A    VOLUNTÁRIO', 'APRENDIZ OPERACIONAL MAX GUANABARA', 'ESTAGIÁRIO', 'TRADE FINANCE PROFESSIONAL', 'ESTAGIÁRIO A  EM B I', 'TÉCNICO DE ENSINO JR  H   ELETRÔNICA  MECATRÔNICA    RP 13495', 'ANALISTA JURÍDICO SR  RJ E FALÊNCIAS ', 'ADVOGADO A  JR ', 'ANALISTA CONTAS A PAGAR JR', 'PROFESSOR A   EDUCADOR A  FÍSICO A ', 'ENGENHEIRO DE PRÉ VENDAS SR', 'EMPACOTADOR  SÃO PAULO   DARK TABARÉ', ' ESPECIALISTA DE TECNOLOGIA ', 'INTERNAL CONTROLS ANALYST', 'CONSULTOR A  TÉCNICO   VW PARK SUL', '10457   ASSISTENTE FISCAL', 'COMMERCIAL ENABLEMENT ASSOCIATE', 'OPERADOR DE RPA  DRONE ', 'ANALISTA DE INTE', 'ANALISTA DE PROCESSOS', 'ANALISTA DE E COMMERCE', 'OPERADOR A  DE CADASTRO   FILIAL 260   AV  DOM PEDRO I  N  2427  BAIRRO  SETOR 5 ', 'RECEPCIONISTA', 'ASSISTENTE FINANCEIRO', 'ANALISTA BI', 'EMPACOTADOR  SÃO PAULO   DARK CONSOLAÇÃO', 'ESTÁGIO EM CONSULTORIA TÉCNICA  INDUSTRIAL    BELO HORIZONTE', 'ANALISTA PROGRAMAR SR', 'CONSULTOR COMERCIAL   INSIDE SALES INBOUND', 'ANALISTA RPA PLENO', 'ELETROTÉCNICO DE MANUTENÇÃO', 'ANALISTA DE RELATÓRIOS', 'ASSISTENTE DE PERECÍVEIS', 'TRADE FINANCE PROFESSIONAL', 'MÉDICO EXAMINADOR   OSASCO SP', 'ANALISTA DE INFO', 'ESTÁGIO EM MERCHANDISING', 'ANALISTA CRO', 'SERVICE DELIVERY MANAGER', 'GERENTE DE CANAIS SP', 'ANALISTA DE GESTÃO DE PESSOAS', 'R D SENIOR ENGINEER   TECHNICAL OWNER', 'TÉCNICO DE CELULAR JUNIOR', 'BUSINESS EXCELENCE', 'BDR COORDINATOR', 'CONSULTOR COMERCIAL   INSIDE SALES LATAM', 'ASSISTENTE PEDAGÓGICO', 'GERENTE COMERCIAL', 'PESSOA TEAM LEADER', 'ANALISTA CRO', 'ENGINEERING MANAGER', 'BALCONISTA   SUPER MUFFATO FOLLONI', 'CUSTOMER EXPERIENCE MANAGER  SÊNIOR    FOUNDING TEAM', 'PRÉ VENDAS  SDR ', 'ANALISTA DE FP A PLENO', 'TÉCNICO DE ENFERMAGEM   LARANJEIRAS RJ', 'KEY ACCOUNT MANAGER SÊNIOR', 'ESTÁGIO   ANÁLISE MACROECONÔMICA', 'SR  PROGRAM MANAGER  DELIVERY EXPERIENCE', 'SOLUÇÕES TECNICAS', 'REDATOR SÊNIOR', 'WAREHOUSE FOREMAN', 'CONSULTOR COMERCIAL   INSIDE SALES OUTBOUND', ' BOLSISTA  GRADUADO   ENG  MECÂNICA   BOSCH   SIMULAÇÕES COMPUTACIONAIS', 'STAFF GAME ENGINEER', 'ANALISTA DE GESTÃO DO CLIENTE I', 'ESTAGIÁRIO', 'MENTOR DE TECNOLOGIA PARA PROGRAMAS DE INOVAÇÃO TECNOLÓGICA', 'PACKET CORE ENGINEER', 'CONSULTOR DE PRÉ VENDAS', 'ANALISTA DE INFORMAÇÕES GERENCIAIS   CLT   PRESENCIAL EM BELO HORIZONTE MG', 'OPERADOR A  DE CADASTRO   FILIAL 200   AV  DOM PEDRO II  1371  BAIRRO  CENTRO', 'CONSULTOR A  SOC   SÃO PAULO', 'ANALISTA PROGRAMAR SR', 'ESTAGIÁRIO', 'KEY ACCOUNT', 'CONSULTOR CLARO', 'AGENTE DE PREVENÇÃO E PERDAS', 'PROFESSOR  A  DE ENFERMAGEM   CAMPINAS SP', 'ABASTECEDOR', 'BRA ESPEC PRODUTOS III', 'BALCONISTA', 'COMUNICADOR VISUAL OPERACIONAL  VIAMÃO  RS', 'ANALISTA DE PROCESSOS', 'MOTORISTA DE VAN', 'P D   ANALISTA DE COMPRAS   HARDWARE', 'ANALISTA DE CONTROLE FINANCEIRO JR ', 'CLIENT PRINCIPAL', 'ANALISTA DE JBP   SEDE', 'ATENDENTE DE SERVIÇO AO CLIENTE SEDE', 'ESPECIALISTA SEGURANCA RED TEAM', 'SENIOR MARKET STRATEGY   PARTNERSHIPS MANAGER', 'CONSULTOR TÉCNICO', 'AJUDANTE DE CARGA E DESCARGA', 'CONSULTOR DE SOLUÇÕES TÉCNICAS', 'VENDEDOR SENIOR', 'HEAD FP A', 'ANALISTA EM GEOPROCESSAMENTO', 'CLOSER SR   VENDEDOR B2B  REMOTO ', 'CONFERENTE  CD EMBU', 'P D   ENGENHEIRO  A  P D   PROJETO E SISTEMA ELETRÔNICO', 'STEWARD   HOTELARIA', 'PACKET CORE ENGINEER', 'SALES ENGINEER', 'ANALISTA DE PREÇOS SEDE', 'CONSULTOR CLARO', 'ANALISTA DE CONTRATOS   PAULINIA   1 VAGA  S   \n2858420  ', 'SOUTH AMERICA ENGAGEMENT LEAD   TRASE', 'PUBLIC SECTOR ACCOUNT MANAGER', 'PRODUCT ENGINEER I', 'CONSULTOR DE PROSPECÇÃO   SDR CLÍNICAS', 'SENIOR RESEARCH ENGINEER', 'ANALISTA FISCAL JUNIOR   SEDE', 'SENIOR CASH MANAGEMENT ANALYST', 'ABASTECEDOR', 'ESTAGIÁRIO A  EM TECNOLOGIA INDUSTRIAL   RJ', 'VAGA FECHADA   CONTADOR A ', 'REPRESENTANTE DE VENDAS  ESPANHOL FLUENTE ', 'ANALISTA NOC SÊNIOR', 'PESSOA ESTAGIÁRIA DE DEPARTAMENTO PESSOAL', 'ANALISTA DE RED TEAM PLENO   VAGA EXCLUSIVA PARA PESSOAS COM DEFICIÊNCIA', 'ANALISTA DE RELACIONAMENTO COM CLIENTE   PLENO', 'SALES SUPERVISOR   B2C   B2B', 'ESPECIALISTA DE TECNOLOGIA  SALESFORCE ', 'PROGRAM MANAGER', 'SCADA ENGINEER', 'PROGRAMA DE ESTÁGIO', 'BDR', 'ESTAGIÁRIO A  DE IMPLANTAÇÃO', 'ANALISTA PROGRAMAR SR', 'CONSULTOR  A  DE UNIDADE   MINAS GERAIS', 'TELECOMUNICAÇÕES', 'CONSULTOR COMERCIAL SÊNIOR   UPSELL', 'PROMOTOR COM MOTO   MOGI DAS CRUZES', 'TECNICO ELETRÔNICO', 'ASSISTENTE DE PROSPECÇÃO   PRÉ VENDA   NOVA LIMA MG', 'ANALISTA DE SOLUÇÕES', 'ANALISTA DE MANUTENÇÃO', 'ANALISTA JÚNIOR DE ESTRATÉGIA   PERFORMANCE', 'ESPECIALISTA EM RPA', 'ENGINEERING MANAGER', 'ASSISTENTE DE FATURAMENTO', 'REDATOR A  SÊNIOR', 'ESTAGIARIO', 'BILLING ANALYST', 'DIRETOR A  DE ARTE SÊNIOR', 'ACCOUNT MANAGER   REMOTE', 'STEWARD   HOTELARIA', 'ESTÁGIO DE LOW CODE', 'NEW GRADUATE HR GENERALIST', 'ANALISTA DE CUSTOS   VALINHOS SP   1 VAGA  S   \n2855042  ', 'REDATOR A  SÊNIOR', 'SENIOR MARKET STRATEGY   PARTNERSHIPS MANAGER', 'ANALISTA DE SUSTENTAÇÃO PLENO', 'SUPERVISOR EXECUCAO AS', 'CONSULTOR  A  DE UNIDADE   MINAS GERAIS', 'MOTORISTA ENTREGADOR   PATOS DE MINAS MG', 'ANALISTA DE RH   R S', 'MENTOR DE TECNOLOGIA PARA PROGRAMAS DE INOVAÇÃO TECNOLÓGICA', 'ANALISTA GESTÃO CATEGORIA   SEDE', 'ANALISTA DE PERFOMANCE', 'CONSULTOR TÉCNICO LEVANTAMENTO HVAC PL', 'PESSOA CONSULTORA DE TREINAMENTOS EUCERIN', 'PESSOA ESTAGIÁRIA DE FORMULAÇÃO', 'WORKFORCE MANAGEMENT ANALYST', 'ASSISTENTE DE COMPRAS', 'ANALISTA DE AUTORIZAÇÕES   RIO DE JANEIRO  RJ   1036674', 'GESTOR DE PROJETOS', 'ANALISTA DE SUSTENTAÇÃO JR   17835', 'ANL JR INFORMAÇÕES GERENCIAIS', 'GERENTE DE MARCA', 'CONSULTOR TÉCNICO DE PRÉ VENDAS SÊNIOR', 'ANALISTA DE PROCESSOS', 'ANALISTA DE LEGAL OPS', 'APRENDIZ OPERACIONAL SAUL', 'PESSOA OPERADORA VOLANTE', 'ASSISTENTE DE ATENDIMENTO   CAMAÇARI BA', 'VENDEDOR  A    JOHN JOHN SOROCABA IGUATEMI ESPLANADA  356622 ', 'JUNIOR SOC PRODUCT ANALYST   ACCURACY ENGINEER', 'ANALISTA ZABBIX JR', 'ANALISTA PLENO DE PLANEJAMENTO FINANCEIRO E ANÁLISE  FP A ', 'JUNIOR RESEARCH ANALYST', 'CONSULTOR CLARO', 'ESTÁGIO EM HARDWARE IN THE LOOP', 'ESTAGIÁRIO', 'ANALISTA DE TREINAMENTO PLENO', 'CONSULTOR TÉCNICO DE PRÉ VENDAS SÊNIOR', 'ANALISTA DE PRÉ VENDAS   OUTBOUND', 'ESTAGIÁRIO', 'ANALISTA FISCAL JÚNIOR   FINANÇAS', 'ANALISTA DE PLANEJAMENTO COMERCIAL PLENO', 'ASSISTENTE FUNCIONAL', 'ABASTECEDOR', 'ESPECIALISTA PLATAFORMA DIGIBEE   18057', 'ASSISTENTE FINANCEIRO', 'ACCOUNT MANAGER', 'ANALISTA DE PLANEJAMENTO FINANCEIRO SR', 'PARTNER MANAGER  CHANNEL ', 'SCADA ENGINEER', 'ENGINEERING MANAGER  TRILOGY  REMOTE     100 000 YEAR USD', 'MEDIA SPECIALIST', 'ANALISTA DE DEPARTAMENTO PESSOAL PL', 'HR ASSISTANT', 'TECNICO EM MANUTENCAO MECANICA', 'SERVICE DELIVERY MANAGER PL', '95878   CONSULTOR TÉCNICO', 'ESPECIALISTA EM SENSORIAMENTO REMOTO', 'CLOSER   VAGA PARA TRABALHAR NO VIDENCI', 'MANOBRISTA   RJ', 'CONSULTOR COMERCIAL SÊNIOR   UPSELL', 'ESPECIALISTA EM INOVAÇÃO', 'LÍDER DE PROJETOS', 'ANALISTA DE PLANEJAMENTO E PERFORMANCE SENIOR', 'ESTÁGIO EM PROJETOS', 'TOPÓGRAFO', 'ANALISTA DE DP', 'PESSOA ASSISTENTE DE GEORREFERENCIAMENTO', 'ESTÁGIO EM MERCHANDISING', 'CONSULTOR TÉCNICO', 'TÉCNICO DE MANUTENÇÃO INDUSTRIAL', '0913   ESTAGIÁRIO   RIBAS DO RIO PARDO', 'INSIDE SALES', 'ANALISTA DE CULTURA E INOVAÇÃO PLENO', 'ASSISTENTE OPERACIONAL II', 'ANALISTA DE TRAFEGO PAGO', 'VENDEDOR SENIOR', 'ANALISTA DE REMUNERAÇÃO SÊNIOR  REMOTO ', 'ANALISTA DE TRAFEGO PAGO', 'ANALISA DE PROJETOS E PROCESSOS', 'ASSISTENTE FINANCEIRO', 'COPEIRO  A    CAMPINAS   10 VAGA  S   \n2859898  ', 'ANALISTA DE SUSTENTAÇÃO JR   17835', 'PRINCIPAL GAMES ENGINEER PT BASED  FAST GROWING SOCIAL GAMES PLATFORM ', 'ESTAGIÁRIO', 'ESTÁGIO EM SUSTENTAÇÃO', 'ADVOGADO IMOBILIÁRIO SR', 'ANALISTA JURÍDICO   PLENO', 'BRAND MANAGER', 'JOVEM APRENDIZ', 'ANALISTA DE PRODUTOS PLENO', 'CONSULTOR DE VENDAS', 'PROGRAMA DE ESTÁGIO', 'ANALISTA EM GEOPROCESSAMENTO', 'PRÉ VENDAS', 'APRENDIZ NOVO HAMBURGO', 'ABASTECEDOR', 'ANALISTA DE ATENDIMENTO FINANCEIRO', 'SENIOR MARKET STRATEGY   PARTNERSHIPS MANAGER', 'PSICÓLOGO', 'SOCIAL LISTENING ANALYST   BELO HORIZONTE', 'ADVOGADO  A  PLENO', 'GERENTE COMERCIAL', 'OPERADOR DE DOBRADEIRA', 'TECHNICAL ACCOUNT MANAGER', 'ANALISTA DE PLANEJAMENTO E CONTROLE DA PRODUÇÃO', 'STAFF GAME ENGINEER', 'ANALISTA CONTÁBIL', 'REDATOR A ', 'AGENTE DE ATENDIMENTO', 'TÉCNICO DE MANUTENÇÃO INDUSTRIAL', '10429   TÉCNICO DE MANUFATURA  ELETRICISTA  PLENO', 'ASSISTENTE DE ENSINO MÉTODO SUPER CÉREBRO', 'COMPUTER VISION ANALYST', 'PESSOA AGENTE DE ATENDIMENTO INTERNO', 'CONTENT PLANNER   REMOTE', 'SERVIÇOS GERAIS   VALINHOS   3 VAGA  S   \n2855270  ', 'ANALISTA DE CONTROLADORIA PLENO', 'ANALISTA DE FP A PLENO', 'JUNIOR RESEARCH ANALYST', 'ANALISTA DE INFORMACOES GERENCIAIS SR', 'GERENTE DE CANAIS SP', 'ENGENHEIRO TÉCNICO DE VENDAS', 'ANALISTA DE REMUNERAÇÃO SÊNIOR  REMOTO ', 'ACCOUNT MANAGER   REMOTE', 'ASSISTENTE DE PCP', 'ENGENHEIRO MECÂNICO ANALISTA DE MANUTENÇÃO', 'ESTAGIÁRIO DE GESTÃO   MERCADO LIVRE DE ENERGIA', 'ANALISTA DE MODELAGEM', 'BALCONISTA', 'OPERADOR DE PROCESSOS', 'KEY ACCOUNT MANAGER SÊNIOR', 'BRAND AND BUSINESS COORDINATOR', 'PLATFORM STAFF ENGINEER', 'ESTÁGIO SINQIA   SÃO PAULO', 'ASSISTENTE DE MANUTENÇÃO   RIO DE JANEIRO', 'RECEPCIONISTA   LABORATÓRIO CLAB', 'FRESADOR CNC', 'REDATOR WEB', 'ANIMATOR', 'ANALISTA DE RELATÓRIOS', 'TECNICO DE ENFERMAGEM DO TRABALHO', 'ANALISTA JÚNIOR DE ESTRATÉGIA   PERFORMANCE', 'HEAD DE PRODUCT OPS', 'AGENTE DE PREVENÇÃO E PERDAS MUFFATO JK LONDRINA PR', 'ESPECIALISTA DE PRODUTO', 'JOVEM APRENDIZ', 'STAFF CONSULTANT', 'INSIDE SALES', 'BOLSISTA DO PROGRAMA INOVA TALENTOS  IEL CNPQ', 'ESPECIALISTA EM EDIÇÃO AUDIOVISUAL EM BARUERI   SP   74854', 'WEBMASTER', 'ESTAGIÁRIO A  DE BI', 'SENIOR PRODUCER', 'PRECEPTOR DE BIOMEDICINA   BANCO DE CURRICULOS', 'ANALISTA SÊNIOR JURÍDICO PARA PROPRIEDADE INTELECTUAL   JURÍDICO E RELAÇÕES GOVERNAMENTAIS', 'INTERNAL CONTROLS ANALYST', 'ANALISTA DE MODELAGEM', 'ANALISTA DE GESTÃO DE PESSOAS', 'ASSISTENTE DE TREINAMENTO', 'É DA ÁREA DE TECNOLOGIA E NÃO ENCONTROU UMA VAGA NO SU PERFIL  SÓ VEM   ', 'TEAM LEAD   TECH', 'ESTAGIÁRIO A  DE FATURAMENTO', 'KEY ACCOUNT MANAGER', 'ANALISTA INSIDE SALES', 'BILLING ANALYST', 'PROMOTOR  A  DE MERCHANDISING  ALIMENTAR  FORTALEZA', 'EMPACOTADOR  SÃO PAULO   DARK CONSOLAÇÃO', 'TORNEIRO MECÂNICO', 'PROFESSOR  A  DE ENFERMAGEM   CAMPINAS SP', 'ANALISTA DE GESTÃO DE PESSOAS', 'COMERCIAL   SUPERVISOR  A  REGIONAL DE VENDAS  NORDESTE ', 'MANOBRISTA   RJ', 'ANALISTA DE PROCESSOS', 'ANALISTA EM CONTROLADORIA E FINANÇAS', 'ESPECIALISTA DE PRÉ VENDAS DE TELECOMUNICAÇÕES   RJ OU SP   HÍBRIDO', 'SEJA UM FRANQUEADO', 'ANALISTA DE SELEÇÃO JÚNIOR', 'ANALISTA DE PRODUTO JÚNIOR', 'STAFF GAME ENGINEER', 'ENGENHARIA   LEAD ENGINEER', 'CUSTOMER EXPERIENCE ASSISTANT', 'ANALISTA DE CONTAS A RECEBER', 'ABASTECEDOR', 'ANALISTA DE CUSTOMER EXPERIENCE JR ', 'CONSULTOR FUNCIONAL JUNIOR UNIFIER', 'TORNEIRO MECÂNICO', 'ANALISTA DE SISTEMA', 'GERENTE DE TECNOLOGIA DA INFORMAÇÃO', 'SENIOR PARTNER MANAGER  CHANNEL ', 'ENTREGADOR', 'ESTÁGIO   CENTRO DE EXCELÊNCIA', 'ESPECIALISTA DE PRÉ VENDAS DE TELECOMUNICAÇÕES   RJ OU SP   HÍBRIDO', 'ANALISTA DE AUTORIZAÇÕES   RIO DE JANEIRO  RJ', 'LÍDER TÉCNICO', 'ANALISTA JURÍDICO', 'ANALISTA DE RPA E BI', 'LÍDER DE NOC', 'OPERADOR DE CENTRO DE USINAGEM', 'CLOSER DE EXPANSÃO', 'ANALISTA DE PERFOMANCE', 'ANALISTA DE EXCELÊNCIA EM MANUFATURA JR', 'CONSULTOR A  DE SUCESSO DO CLIENTE   UBERLÂNDIA MG  UNIDADE VIRTUAL ', 'ANALISTA DE PRODUÇÃO', 'DEMO ENGINEER   BRAZIL', 'ANALISTA DE CONTAS A PAGAR E RECEBER JÚNIOR', 'AVP   NON FINANCIAL RISK MANAGEMENT COVERAGE', 'ESPECIALISTA EM INOVAÇÃO', 'ESTAGIÁRIO DE GESTÃO   MERCADO LIVRE DE ENERGIA', 'ESTAGIÁRIO DE PRODUTOS   APM', 'TÉCNICO DE MANUTENÇÃO INDUSTRIAL', 'ANALISTA DE CONTEUDO JUNIOR', 'SUPERVISOR EXECUCAO AS', 'ANALISTA DE CUSTOS', 'INTERNAL CONTROLS ANALYST', 'LÍDER DE VENDAS B2B', 'LEAD PHP', 'ANALISTA DE PROGRAMAÇÃO JR', 'TÉCNICO DE ENFERMAGEM DO TRABALHO   LONDRINA PR', 'AGENTE DE PREVENÇÃO E PERDAS SAUL', 'ANALISTA FINOPS   PLENO', 'SUPERVISOR GERAL', 'MEDIA BUY MANAGER', 'É DA ÁREA DE TECNOLOGIA E NÃO ENCONTROU UMA VAGA NO SU PERFIL  SÓ VEM   ', 'ESPECIALISTA DE PROCESSOS E PROJETOS', 'AMAZON ASSISTANT', 'BDR ANALYST SR ', 'ESPECIALISTA DE PRODUTO   MERCADO PAGO', 'ANALISTA BI', 'SECRETÁRIA PLENO', 'PROFESSOR  A  DE RADIOLOGIA   SOROCABA', 'CONSULTOR DE VENDAS INTERNO', 'PAID ADS MARKETER  REMOTE ', 'ESPECIALISTA EM INOVAÇÃO', 'TÉCNICO DE ENFERMAGEM   RIO DE JANEIRO RJ', 'ASSISTENTE OPERACIONAL II  COMEX    12 36 NOTURNO', 'ATENDIMENTO AO CLIENTE  SAC SEDE', 'ANALISTA DE TRAFEGO PAGO   CAMPINAS   1 VAGA  S   \n2857523  ', 'PESSOA ESTAGIÁRIA DE FORMULAÇÃO', 'TECHNICAL TEAM LEAD  TRILOGY  REMOTE     100 000 YEAR USD', 'APRENDIZ OPERACIONAL AURORA', 'CONSULTOR DE PRÉ VENDAS', 'SDR', 'CONSULTOR DE VENDAS', 'ASSISTANT MANAGER', 'BALCONISTA DE PADARIA   GLICÉRIO', 'ASSISTENTE CONTÁBIL', 'ANALISTA DE CONTEUDO JUNIOR', 'CONSULTOR', 'ASSISTENTE COMERCIAL', 'ANALISTA DE TREINAMENTO PL ', 'ANALISTA DE EXCELÊNCIA OPERACIONAL E PROJETOS SÊNIOR', 'ANALISTA DE REDAÇÃO', 'CONSULTOR COMERCIAL', 'ESTAGIÁRIO DE ENGENHARIA QUÍMICA', 'ELETROTÉCNICO DE MANUTENÇÃO', 'ANALISTA DE CADASTRO JURÍDICO   JÚNIOR', '10429   TÉCNICO DE MANUFATURA  ELETRICISTA  PLENO', 'ANALISTA DE DHO   FOCO EM TREINAMENTO', 'APRENDIZ OPERACIONAL   MUFFATO CAFEZAL', 'SUPERVISOR COMERCIAL', 'ANALISTA DE REMUNERAÇÃO SÊNIOR  REMOTO ', 'ATENDENTE DE PADARIA AÇOUGUE', 'ESPECIALISTA EM SENSORIAMENTO REMOTO', 'PROFESSOR FAC I   RPS 13068 E 13302', 'BUSINESS EXCELENCE', 'GERENTE DE RELACIONAMENTO', 'ANALYST  BIOENERGY  BIOFUELS RESEARCH', 'ASSISTENTE DE SERVICE DESK JR', 'SERVICE DELIVERY MANAGER PL', 'ESPECIALISTA SEGURANCA RED TEAM', 'ENTREGADOR', 'ESPECIALISTA DE PRÉ VENDAS DE TELECOMUNICAÇÕES   RJ OU SP   HÍBRIDO', 'CLOSER HOME OFFICE  PJ  PARA SAAS', 'PROGRAMA DE ESTÁGIO', 'ANL JR INFORMAÇÕES GERENCIAIS', 'ANALYST  WORK FROM HOME ', 'AGENTE DE ATENDIMENTO', 'ASSISTENTE PEDAGÓGICO', '0719 0008 ASSISTENTE DE ATENDIMENTO   MALLET  PR ', 'EMPACOTADOR  SÃO PAULO   DARK CONSOLAÇÃO', 'ESTÁGIO EM MERCHANDISING', 'EMPACOTADOR  SÃO PAULO   DARK TABARÉ', 'RECEPCIONISTA', 'GERENTE DE CONTAS   SÃO PAULO', 'SALES ENGINEER', 'ANALISTA DE OBSERVABILIDADE JUNIOR', 'ENGENHEIRO DE PROCESSOS E AUTOMAÇÃO', 'COPEIRO  A ', 'ANALISTA DE CUSTOS', 'ANGULAR ENGINEER   WORK FROM HOME', 'CONSULTOR COMERCIAL   INSIDE SALES LATAM', 'ANALISTA DE PRODUTO JÚNIOR', 'RELEASE MANAGER PLENO', 'ANALISTA DE RELATÓRIOS', 'ESPECIALISTA DE PRODUTO   MERCADO PAGO', 'ATENDENTE', 'ANALISTA FISCAL PLENO   SEDE', 'SR  TECHNICAL ACCOUNT MANAGER', 'DIRETOR DE PÓS VENDAS', 'ANALISTA PRODUTO E INT MERCADO JR', 'PRÉ VENDAS', 'ESTAGIÁRIO COMERCIAL', 'PROGRAMA DE ESTÁGIO', 'ANALISTA DE RELATÓRIOS', 'SEARCH ENGINE ENGINEER', 'COMPRADOR JÚNIOR  SERVIÇOS ', 'P D   DESENHISTA MECÂNICO', 'ASSISTENTE ROTEIRIZAÇÃO', 'LÍDER OPERACIONAL DE ESTACIONAMENTO   CAMPINAS', 'ANALISTA DE CONTAS A PAGAR E RECEBER JÚNIOR', 'ANALISTA DE PLANEJAMENTO DE OBRAS', 'ESTAGIÁRIO   WEB CONTENT', 'ESTÁGIO EM MERCHANDISING', 'ABASTECEDOR', 'CHANNEL PARTNER MANAGER', ' NET JR', 'PROMOTOR DE VENDAS  COM CARRO', 'COMMERCIAL PARTNERSHIP LATAM', 'CONSULTOR A  DE PROJETOS', 'ANALISTA DE IMPLANTAÇÃO FISCAL CONTÁBIL', 'ANALISTA DE ATENDIMENTO AO CLIENTE   SÃO PAULO SP', 'ASSISTENTE COMERCIAL', 'SENIOR SERVICE INTEGRATOR', 'TÉCNICO A  EM LABORATÓRIO', 'ANALISTA DE PROCESSOS I', 'EMPACOTADOR  SÃO PAULO   DARK CONSOLAÇÃO', 'ASSISTENTE DE PRODUTOS', 'ANALISTA JURÍDICO PL SR  NPL ', 'ESTAGIÁRIO', 'GERENTE DE CANAIS COMERCIAL NACIONAL', 'ANALISTA FUNCIONAL SR   RPA', 'GERENTE COMERCIAL SR', 'ANALISTA COMERCIAL', 'ANALISTA PROTHEUS', 'CONFERENTE DE EXPEDIÇÃO', 'ANALISTA DE PRODUTO JÚNIOR', 'REPRESENTANTE DE ATENDIMENTO AO CLIENTE', 'ASSISTENTE DE MANUTENÇÃO   RIO DE JANEIRO', 'RECEPCIONISTA   LABORATÓRIO CLAB', 'STAFF GAME ENGINEER', 'ESTAGIÁRIO', 'ENGENHEIRO DE PRODUÇÃO', 'VISTORIADOR A  PROJETO SERVIÇO', 'CONSULTOR TÉCNICO', 'ATENDENTE', 'ESTÁGIO DE LOW CODE', 'ANALISTA DE RELAÇÕES GOVERNAMENTAIS E INTERNACIONAIS', 'CONSULTOR A  SOC   SÃO PAULO', 'CONSULTOR COMERCIAL', 'ANALISTA COMERCIAL PLENO', 'VAGA TRAINEE MODELO', 'SAS PROGRAMMER I', 'FIELD TECHNICIAN', 'ASSISTENTE DE PRODUÇÃO   SUMARÉ   1 VAGA  S   \n2859594  ', 'ANALISTA CONTROLES INTERNO', 'ESTAGIÁRIO', 'CONSULTOR A  SUCESSO DO CLIENTE', 'LEAD PHP', 'ESTAGIÁRIO', 'ESTAGIÁRIO A ', 'PACKET CORE ENGINEER', 'ASSISTENTE DE BENEFÍCIOS', 'JOVEM APRENDIZ ASSIST ADM', 'ANALISTA DE AUTORIZAÇÕES   RIO DE JANEIRO  RJ   1036674', 'ESTÁGIO DE RH', 'ATENDIMENTO AO CLIENTE  SAC SEDE', 'GESTÃO DE TELECOMUNICAÇÕES', 'É DA ÁREA DE TECNOLOGIA E NÃO ENCONTROU UMA VAGA NO SU PERFIL  SÓ VEM   ', 'ABASTECEDOR', 'ABASTECEDOR', 'LATAM SALES PARTNER MANAGER', 'LÍDER DE PROJETOS', 'ASSISTENTE FINANCEIRO   CONTAS A PAGAR', 'MANOBRISTA   RJ', 'ANALISTA SOC JR', 'ANALISTA DE PROCESSOS I', 'GERENTE PLANEJAMENTO CONFIABILIDADE MANUTENÇÃO USINA', 'ASSISTENTE DE PROSPECÇÃO  SDR    MACEIÓ   AL  ', 'ASSISTENTE SAC   C C MORUMBI', 'ESPECIALISTA DE OFERTAS  PRÉ VENDAS ', 'ANALISTA DE MATERIAIS', 'CONSULTOR A  SOC   SÃO PAULO', 'TRADE FINANCE PROFESSIONAL', 'ANALISTA ZABBIX JR', 'ANALISTA SEGURIDADE PLENO', 'BILLING ANALYST', 'PROFESSOR DE SOLUÇÕES TECNOLÓGICAS', 'ANALISTA DE PRODUTO JÚNIOR', 'CONSULTOR DE VENDAS', 'ASSISTENTE DE PERECÍVEIS', 'ATENDENTE DE PADARIA AÇOUGUE', 'ANALISTA DE MANUTENÇÃO II', 'ESPECIALISTA DE PRODUTO   MERCADO PAGO', 'SUPERVISOR A  JURÍDICO A ', 'ESPECIALISTA DE RELAÇÕES PÚBLICAS', 'ENGENHEIRO DE PRÉ VENDAS SR', 'VALUE STREAM PLENO', 'COMMERCIAL ENABLEMENT ASSOCIATE', 'ANALISTA DE FINANCE TRADING', 'EMAIL MARKETER', 'ANALYST', 'ESPECIALISTA FINANCEIRO II  TERCEIRO ', 'ANALISTA DE JORNADA DO CLIENTE', 'FINANCE PLANNING INTERN', 'JOVEM APRENDIZ', 'REDATOR A ', 'CONSULTOR TÉCNICO DE PRÉ VENDAS SÊNIOR', 'ENTREGADOR', 'ANALISTA DE MANUTENÇÃO', 'ASSISTENTE CONTÁBIL', 'CONSULTOR DE PROSPECÇÃO   SDR CLÍNICAS', 'LÍDER OPERACIONAL DE ESTACIONAMENTO   CAMPINAS', 'CONSULTOR TÉCNICO DE VEÍCULOS', 'PRÉ VENDAS', 'ANALISTA COMERCIAL  FARMER    VAGA PRESENCI

In [917]:
# Excluindo linhas em que a Categorias é "OUTRO", "Banco de Talentos", "Marketing Digital", "Suporte Técnico"
df = df.loc[df['Categoria'] != 'MARKETING/DIGITAL'] 
df = df.loc[df['Categoria'] != 'OUTROS']
df = df.loc[df['Categoria'] != 'BANCO DE TALENTOS']
df = df.loc[df['Categoria'] != 'SUPORTE TÉCNICO']
df = df.loc[df['Categoria'] != 'ANALISTAS DE NEGÓCIOS']

### Criando sub-categorias

In [918]:
# Função para verificar a sub-Categoria da vaga

def sub_categorizar_vaga(Titulo):
    if ('DATA' in Titulo or 'DADOS' in Titulo or 'DATOS' in Titulo) and ('ENGINEER' in Titulo or 'ENGENHEIR' in Titulo or 'ENGENHARIA' in Titulo):
        return 'ENGENHARIA DE DADOS'
    elif ('DATA' in Titulo or 'DADOS' in Titulo or 'DATOS' in Titulo) and ('SCIENCE' in Titulo or 'CIÊNCIA' in Titulo or 'CIENTISTA' in Titulo or 'SCIENTIST' in Titulo):
        return 'CIÊNCIA DE DADOS'
    elif ('DATA' in Titulo or 'DADOS' in Titulo or 'DATOS' in Titulo or ' BI ' in Titulo) and ('ANALYST' in Titulo or 'ANÁLISE' in Titulo or 'ANALISE' in Titulo or 'ANALYSIS' in Titulo):
        return 'ANALISTA DE DADOS'
    elif ('DESENVOLVEDOR' in Titulo or 'DEVELOPER' in Titulo or 'PROGRAMADOR' in Titulo or 'DESENVOLVIMENTO' in Titulo or 'DEV' in Titulo) and ('STACK' in Titulo):
        return 'FULL STACK'
    elif ('DESENVOLVEDOR' in Titulo or 'DEVELOPER' in Titulo or 'PROGRAMADOR' in Titulo or 'DESENVOLVIMENTO' in Titulo or 'DEV' in Titulo) and ('FRONT' in Titulo):
        return 'FRONT END'
    elif ('DESENVOLVEDOR' in Titulo or 'DEVELOPER' in Titulo or 'PROGRAMADOR' in Titulo or 'DESENVOLVIMENTO' in Titulo or 'DEV' in Titulo) and ('BACK' in Titulo):
        return 'BACK END'
    elif ('DESENVOLVEDOR' in Titulo or 'DEVELOPER' in Titulo or 'PROGRAMADOR' in Titulo or 'DESENVOLVIMENTO' in Titulo or 'DEV' in Titulo) and ('MOBILE' in Titulo):
        return 'MOBILE'

    # Se nenhuma correspondência for encontrada, você pode retornar algo como 'outro' ou None
    return 'OUTRO'

# Aplicando a função à coluna 'título' para criar a coluna 'Categoria'
df['Sub_Categoria'] = df['Titulo'].apply(sub_categorizar_vaga)

# Exibindo o DataFrame resultante
df.head(3)

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\300476840.py:23: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

,Titulo,Link_vaga,Link_empresa,Empresa,Data_divulgação,Candidaturas,Descricao,Senioridade,Tipo,Funcao,...,TYPESCRIPT,TESTE,UI,UNIX,UX,VIRTUALIZATION,VUE,WORDPRESS,Categoria,Sub_Categoria
0,DESENVOLVEDOR A FRONTEND JUNIOR,https://br.linkedin.com/jobs/view/desenvolvedo...,https://br.linkedin.com/company/zenvia-inc?trk...,ZENVIA,2024-01-10,200,O TIME DE ATTRACTION TEM A MISSÃO DE ANALISAR ...,ASSISTENTE,TEMPO INTEGRAL,ENGENHARIA E TECNOLOGIA DA INFORMAÇÃO,...,0,0,0,0,0,0,1,0,DESENVOLVIMENTO,FRONT END
1,DESENVOLVEDOR DATAVIZ JR HIBRIDO FARIA LIM...,https://br.linkedin.com/jobs/view/desenvolvedo...,https://br.linkedin.com/company/iterative-?trk...,ITERATIVE,2023-12-27,25,DATA VIZ JR \nRESPONSABILIDADES\nATUAR COMO SU...,PLENO-SÊNIOR,TEMPO INTEGRAL,ENGENHARIA E TECNOLOGIA DA INFORMAÇÃO,...,0,0,0,0,0,0,0,0,DESENVOLVIMENTO,OUTRO
2,ESTÁGIO DESENVOLVEDOR A JAVA,https://br.linkedin.com/jobs/view/est%C3%A1gio...,https://br.linkedin.com/company/meisters-solut...,MEISTERS SOLUTIONS,2024-01-08,0,NÍVEL ESTAGIÁRIO\nCURSOS DE ANÁLISE E DESENV...,ESTÁGIO,TEMPO INTEGRAL,ENGENHARIA E TECNOLOGIA DA INFORMAÇÃO,...,0,0,0,0,0,0,0,0,DESENVOLVIMENTO,OUTRO

### Verificando modelo de trabalho de acordo com descrição

In [919]:
# Função para verificar se a vaga é remota, híbrida ou presencial

def modelo(descricao):
    if 'REMOTO' in descricao or 'HOME' in descricao or 'REMOTE' in descricao or 'TELETRABALHO' in descricao:
        return 'REMOTO'
    elif 'HÍBRIDO' in descricao or 'HIBRIDO' in descricao or 'HÍBRIDA' in descricao or 'HYBRID' in descricao:
        return 'HÍBRIDO'
    elif 'PRESENCIAL' in descricao or 'ON-SITE' in descricao or 'IN-PERSON' in descricao:
        return 'PRESENCIAL'

    # Se nenhuma correspondência for encontrada, retornar OUTRO
    return 'OUTRO'

# Aplicando a função à coluna 'Descricao' para criar a coluna 'tipo_loc'
df['modelo'] = df['Descricao'].apply(modelo)

# Exibindo o DataFrame resultante
df

C:\Users\laris\AppData\Local\Temp\ipykernel_64504\4118741603.py:15: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

,Titulo,Link_vaga,Link_empresa,Empresa,Data_divulgação,Candidaturas,Descricao,Senioridade,Tipo,Funcao,...,TESTE,UI,UNIX,UX,VIRTUALIZATION,VUE,WORDPRESS,Categoria,Sub_Categoria,modelo
0,DESENVOLVEDOR A FRONTEND JUNIOR,https://br.linkedin.com/jobs/view/desenvolvedo...,https://br.linkedin.com/company/zenvia-inc?trk...,ZENVIA,2024-01-10,200,O TIME DE ATTRACTION TEM A MISSÃO DE ANALISAR ...,ASSISTENTE,TEMPO INTEGRAL,ENGENHARIA E TECNOLOGIA DA INFORMAÇÃO,...,0,0,0,0,0,1,0,DESENVOLVIMENTO,FRONT END,REMOTO
1,DESENVOLVEDOR DATAVIZ JR HIBRIDO FARIA LIM...,https://br.linkedin.com/jobs/view/desenvolvedo...,https://br.linkedin.com/company/iterative-?trk...,ITERATIVE,2023-12-27,25,DATA VIZ JR \nRESPONSABILIDADES\nATUAR COMO SU...,PLENO-SÊNIOR,TEMPO INTEGRAL,ENGENHARIA E TECNOLOGIA DA INFORMAÇÃO,...,0,0,0,0,0,0,0,DESENVOLVIMENTO,OUTRO,HÍBRIDO
2,ESTÁGIO DESENVOLVEDOR A JAVA,https://br.linkedin.com/jobs/view/est%C3%A1gio...,https://br.linkedin.com/company/meisters-solut...,MEISTERS SOLUTIONS,2024-01-08,0,NÍVEL ESTAGIÁRIO\nCURSOS DE ANÁLISE E DESENV...,ESTÁGIO,TEMPO INTEGRAL,ENGENHARIA E TECNOLOGIA DA INFORMAÇÃO,...,0,0,0,0,0,0,0,DESENVOLVIMENTO,OUTRO,REMOTO
3,DESENVOLVEDOR FRONT END JR,https://br.linkedin.com/jobs/view/desenvolvedo...,https://br.linkedin.com/company/neooh?trk=publ...,NEOOH,2024-01-06,200,DESCRIÇÃO\nPARTICIPAR DO DESENVOLVIMENTO DE NO...,JÚNIOR,TEMPO INTEGRAL,TECNOLOGIA DA INFORMAÇÃO,...,0,0,0,0,0,0,0,DESENVOLVIMENTO,FRONT END,REMOTO
4,DESENVOLVEDOR FULL STACK,https://br.linkedin.com/jobs/view/desenvolvedo...,https://br.linkedin.com/company/g4fbr?trk=publ...,G4F,2023-12-21,200,VENHA FAZER PARTE DA G4F \nA G4F TRABALHA HÁ M...,PLENO-SÊNIOR,TEMPO INTEGRAL,TECNOLOGIA DA INFORMAÇÃO,...,0,0,0,0,0,0,0,DESENVOLVIMENTO,FULL STACK,HÍBRIDO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7738,PROGRAMADOR E OPERADOR DE TORNO CNC,https://br.linkedin.com/jobs/view/programador-...,https://br.linkedin.com/company/burh?trk=publi...,BURH,2024-01-17,25,TÍTULO DO CARGO OPERADOR DE TORNO CNC SETOR ...,ASSISTENTE,NÃO INFORMADO,ENGENHARIA E TECNOLOGIA DA INFORMAÇÃO,...,0,0,0,0,0,0,0,DESENVOLVIMENTO,OUTRO,OUTRO
7739,PROGRAMADOR WEB BACKEND SENIOR,https://br.linkedin.com/jobs/view/programador-...,https://fr.linkedin.com/company/leroy-merlin?t...,LEROY MERLIN,2024-01-17,0,ESTAMOS PROCURANDO NOVOS INTEGRANTES PARA NOSS...,PLENO-SÊNIOR,NÃO INFORMADO,ENGENHARIA E TECNOLOGIA DA INFORMAÇÃO,...,0,0,0,0,0,0,0,DESENVOLVIMENTO,BACK END,OUTRO
7740,PROGRAMADOR CLIPPER PL SR,https://br.linkedin.com/jobs/view/programador-...,https://br.linkedin.com/company/iventis?trk=pu...,IVENTIS,2024-02-06,25,PRESENCIAL HIBRIDO 3X POR SEMANA EM CAMPINAS S...,PLENO-SÊNIOR,NÃO INFORMADO,ENGENHARIA E TECNOLOGIA DA INFORMAÇÃO,...,0,0,0,0,0,0,0,DESENVOLVIMENTO,OUTRO,HÍBRIDO
7741,OPERADOR E PROGRAMADOR DE CENTRO DE USINAGEM ...,https://br.linkedin.com/jobs/view/operador-e-p...,https://br.linkedin.com/company/burh?trk=publi...,BURH,2024-01-17,25,1 INFORMAÇÕES DO CARGO\nTÍTULO DO CARGO OPER...,ASSISTENTE,NÃO INFORMADO,GERENCIAMENTO E MANUFATURA,...,0,0,0,0,0,0,0,DESENVOLVIMENTO,OUTRO,OUTRO
7743,FRESADOR PROGRAMADOR CNC,https://br.linkedin.com/jobs/view/fresador-pro...,https://www.linkedin.com/company/kse-servicos-...,GRUPO KSE,2024-02-06,25,ATUAR EM FRESADORA CNC DE PREFERÊNCIA NAS MAQ...,ASSISTENTE,NÃO INFORMADO,ENGENHARIA E TECNOLOGIA DA INFORMAÇÃO,...,0,0,0,0,0,0,0,DESENVOLVIMENTO,OUTRO,OUTRO

## <center>Cálculos e Análises

### Análise de vagas

In [920]:
# Distruibuição de vagas por categoria
print("Análise de Oferta: Distribuição de Vagas por Categoria")
vagas_categoria = df["Categoria"].value_counts().reset_index()
vagas_categoria.columns = ["Categoria", "Numero_Vagas"]
print(vagas_categoria)

Análise de Oferta: Distribuição de Vagas por Categoria
                 Categoria  Numero_Vagas
0          DESENVOLVIMENTO          3023
1     ANALISTA DE SISTEMAS          1549
2                 DADOS/BI           734
3             DESIGN/UX/UI           620
4                LIDERANÇA           164
5       CLOUD/DEVOPS/INFRA           160
6  SEGURANÇA DA INFORMAÇÃO            77
7         QUALIDADE/TESTES            61

In [921]:
# Distribuição de vagas por senioridade
print("Análise de Oferta: Distribuição de Vagas por Senioridade")
vagas_senioridade = df["Senioridade"].value_counts().reset_index()
vagas_senioridade.columns = ["Senioridade", "Numero_Vagas"]
print(vagas_senioridade)

Análise de Oferta: Distribuição de Vagas por Senioridade
     Senioridade  Numero_Vagas
0     ASSISTENTE          3141
1   PLENO-SÊNIOR          2439
2  NÃO INFORMADO           416
3        ESTÁGIO           227
4         JÚNIOR           165

In [922]:
# Distribuição de vagas por modelo de trabalho
print("Análise de Oferta: Distribuição de Vagas por Modelo de Trabalho")
vagas_modelo = df["modelo"].value_counts().reset_index()
vagas_modelo.columns = ["Modelo", "Numero_Vagas"]
print(vagas_modelo)

Análise de Oferta: Distribuição de Vagas por Modelo de Trabalho
       Modelo  Numero_Vagas
0       OUTRO          3714
1      REMOTO          1694
2     HÍBRIDO           550
3  PRESENCIAL           430

### Análise de Candidaturas

In [923]:
# Calculando a média do número de candidaturas por categoria de vaga

Calc_Cand_Vaga_cat = df.groupby('Categoria').agg(
    Quantidade=('Categoria', 'count'),
    Soma_Candidaturas=('Candidaturas', 'sum')
).reset_index()
Calc_Cand_Vaga_cat['Cand_Vaga'] = Calc_Cand_Vaga_cat['Soma_Candidaturas'] / Calc_Cand_Vaga_cat['Quantidade']
Calc_Cand_Vaga_cat = Calc_Cand_Vaga_cat.sort_values(by='Cand_Vaga', ascending=True)

# Exibir o DataFrame resultante
print(Calc_Cand_Vaga_cat)

                 Categoria  Quantidade  Soma_Candidaturas  Cand_Vaga
1       CLOUD/DEVOPS/INFRA         160               4182  26.137500
2                 DADOS/BI         734              23623  32.183924
3          DESENVOLVIMENTO        3023              99047  32.764472
4             DESIGN/UX/UI         620              22080  35.612903
6         QUALIDADE/TESTES          61               2200  36.065574
0     ANALISTA DE SISTEMAS        1549              57936  37.402195
5                LIDERANÇA         164               7639  46.579268
7  SEGURANÇA DA INFORMAÇÃO          77               4662  60.545455

In [924]:
# Calculando o número de candidaturas por vaga por categoria e nível de senioridade
Calc_Cand_Vaga_cat = df.groupby(['Categoria', 'Senioridade']).agg(
    Quantidade_Vagas=('Categoria', 'count'),  # Soma o número de vagas
    Soma_Candidaturas=('Candidaturas', 'sum')
).reset_index()

# Calculando candidaturas por vaga (média)
Calc_Cand_Vaga_cat['Cand_Vaga'] = Calc_Cand_Vaga_cat['Soma_Candidaturas'] / Calc_Cand_Vaga_cat['Quantidade_Vagas']

# Ordenando por candidaturas por vaga (do maior para o menor)
Calc_Cand_Vaga_cat = Calc_Cand_Vaga_cat.sort_values(by='Cand_Vaga', ascending=False)

# Formatando para melhor visualização
Calc_Cand_Vaga_cat['Cand_Vaga'] = Calc_Cand_Vaga_cat['Cand_Vaga'].round(2)

# Exibir o DataFrame resultante
Calc_Cand_Vaga_cat

,Categoria,Senioridade,Quantidade_Vagas,Soma_Candidaturas,Cand_Vaga
36,SEGURANÇA DA INFORMAÇÃO,JÚNIOR,5,600,120.00
31,QUALIDADE/TESTES,JÚNIOR,4,400,100.00
16,DESENVOLVIMENTO,JÚNIOR,51,4257,83.47
21,DESIGN/UX/UI,JÚNIOR,14,1058,75.57
27,LIDERANÇA,NÃO INFORMADO,9,675,75.00
38,SEGURANÇA DA INFORMAÇÃO,PLENO-SÊNIOR,48,3249,67.69
28,LIDERANÇA,PLENO-SÊNIOR,85,4949,58.22
30,QUALIDADE/TESTES,ESTÁGIO,5,284,56.80
1,ANALISTA DE SISTEMAS,ESTÁGIO,88,4627,52.58
10,DADOS/BI,ESTÁGIO,38,1869,49.18
23,DESIGN/UX/UI,PLENO-SÊNIOR,146,6804,46.60
33,QUALIDADE/TESTES,PLENO-SÊNIOR,25,1059,42.36
15,DESENVOLVIMENTO,ESTÁGIO,54,2248,41.63
17,DESENVOLVIMENTO,NÃO INFORMADO,162,6692,41.31
2,ANALISTA DE SISTEMAS,JÚNIOR,45,1848,41.07
4,ANALISTA DE SISTEMAS,PLENO-SÊNIOR,730,29559,40.49
34,SEGURANÇA DA INFORMAÇÃO,ASSISTENTE,17,687,40.41
18,DESENVOLVIMENTO,PLENO-SÊNIOR,930,37024,39.81
24,LIDERANÇA,ASSISTENTE,49,1940,39.59
0,ANALISTA DE SISTEMAS,ASSISTENTE,577,19723,34.18
13,DADOS/BI,PLENO-SÊNIOR,380,12978,34.15
19,DESIGN/UX/UI,ASSISTENTE,344,10968,31.88
20,DESIGN/UX/UI,ESTÁGIO,34,992,29.18
11,DADOS/BI,JÚNIOR,22,637,28.95
8,CLOUD/DEVOPS/INFRA,PLENO-SÊNIOR,95,2740,28.84
9,DADOS/BI,ASSISTENTE,267,7642,28.62
22,DESIGN/UX/UI,NÃO INFORMADO,82,2258,27.54
6,CLOUD/DEVOPS/INFRA,JÚNIOR,7,192,27.43
14,DESENVOLVIMENTO,ASSISTENTE,1826,48826,26.74
5,CLOUD/DEVOPS/INFRA,ASSISTENTE,40,900,22.50
3,ANALISTA DE SISTEMAS,NÃO INFORMADO,109,2179,19.99
7,CLOUD/DEVOPS/INFRA,NÃO INFORMADO,18,350,19.44
29,QUALIDADE/TESTES,ASSISTENTE,21,407,19.38
35,SEGURANÇA DA INFORMAÇÃO,ESTÁGIO,4,76,19.00
25,LIDERANÇA,ESTÁGIO,4,75,18.75
12,DADOS/BI,NÃO INFORMADO,27,497,18.41
37,SEGURANÇA DA INFORMAÇÃO,NÃO INFORMADO,3,50,16.67
32,QUALIDADE/TESTES,NÃO INFORMADO,6,50,8.33
26,LIDERANÇA,JÚNIOR,17,0,0.00

In [925]:
# Média de Candidaturas por categoria
print("Média de Candidaturas por Categoria")
candidaturas_categoria = df.groupby("Categoria")["Candidaturas"].mean().reset_index()
candidaturas_categoria.columns = ["Categoria", "Media_Candidaturas"]
print(candidaturas_categoria.sort_values(by="Media_Candidaturas", ascending=False))

Média de Candidaturas por Categoria
                 Categoria  Media_Candidaturas
7  SEGURANÇA DA INFORMAÇÃO           60.545455
5                LIDERANÇA           46.579268
0     ANALISTA DE SISTEMAS           37.402195
6         QUALIDADE/TESTES           36.065574
4             DESIGN/UX/UI           35.612903
3          DESENVOLVIMENTO           32.764472
2                 DADOS/BI           32.183924
1       CLOUD/DEVOPS/INFRA           26.137500

In [926]:
# Média de Candidaturas por senioridade
print("Média de Candidaturas por Senioridade")
candidaturas_senioridade = df.groupby("Senioridade")["Candidaturas"].mean().reset_index()
candidaturas_senioridade.columns = ["Senioridade", "Media_Candidaturas"]
print(candidaturas_senioridade.sort_values(by="Media_Candidaturas", ascending=False))

Média de Candidaturas por Senioridade
     Senioridade  Media_Candidaturas
2         JÚNIOR           54.496970
1        ESTÁGIO           44.806167
4   PLENO-SÊNIOR           40.328823
3  NÃO INFORMADO           30.651442
0     ASSISTENTE           29.001273

In [927]:
# Média de candidaturas por modelo de trabalho
print("Média de Candidaturas por Modelo de Trabalho")
candidaturas_modelo = df.groupby("modelo")["Candidaturas"].mean().reset_index()
candidaturas_modelo.columns = ["Modelo", "Media_Candidaturas"]
print(candidaturas_modelo.sort_values(by="Media_Candidaturas", ascending=False))

Média de Candidaturas por Modelo de Trabalho
       Modelo  Media_Candidaturas
0     HÍBRIDO           38.509091
3      REMOTO           38.219599
1       OUTRO           33.244750
2  PRESENCIAL           27.846512

### Habilidades por categoria

In [928]:
# Análise de Habilidades por Profissão (Top 5 habilidades por Categoria de Vaga)
print("Análise de Habilidades por Profissão:")
for categoria in df["Categoria"].unique():
    print(f"Top 5 Habilidades para {categoria}:")
    df_categoria = df[df["Categoria"] == categoria]
    # Filtrar apenas as colunas de habilidades
    habilidades_cols = [col for col in df_categoria.columns if col in habilidades_tecnicas]
    if not habilidades_cols:
        print("Nenhuma habilidade encontrada para esta categoria.")
        continue
    habilidades_contagem_categoria = df_categoria[habilidades_cols].sum().sort_values(ascending=False)
    print(habilidades_contagem_categoria.head(5))

Análise de Habilidades por Profissão:
Top 5 Habilidades para DESENVOLVIMENTO:
FRONT     540
BACK      398
CLOUD     341
REACT     322
SQL       311
dtype: int64
Top 5 Habilidades para ANALISTA DE SISTEMAS:
CLOUD                201
SQL                  123
AUTOMAÇÃO            119
MACHINE LEARNING      95
PYTHON                94
dtype: int64
Top 5 Habilidades para SEGURANÇA DA INFORMAÇÃO:
CLOUD     20
LINUX      8
AWS        7
C          7
CI         6
dtype: int64
Top 5 Habilidades para QUALIDADE/TESTES:
TESTE         17
AUTOMAÇÃO     15
QA            11
API            9
AGILE          7
dtype: int64
Top 5 Habilidades para CLOUD/DEVOPS/INFRA:
CLOUD         72
AWS           36
AUTOMAÇÃO     26
LINUX         25
CI            18
dtype: int64
Top 5 Habilidades para DADOS/BI:
SQL                  189
CLOUD                 95
PYTHON                76
MACHINE LEARNING      72
ETL                   60
dtype: int64
Top 5 Habilidades para LIDERANÇA:
ENGLISH     28
AGILE       24
CLOUD       20
UX          20
SCRUM       17
dtype: int64
Top 5 Habilidades para DESIGN/UX/UI:
UX            177
UI            117
PHOTOSHOP      30
AGILE          24
FIGMA          24
dtype: int64

## <center>Visualização de dados

### Distribuição de vagas por categoria, senioridade e modelo de trabalho

In [929]:
# Distribuição de Vagas por Categoria
# Primeiro criamos um DataFrame com as contagens
contagens = df["Categoria"].value_counts().reset_index()
contagens.columns = ["Categoria", "Contagem"]  # Renomeando as colunas para maior clareza

# Criando o gráfico
fig = px.bar(contagens, 
             x="Categoria", 
             y="Contagem",
             labels={"Categoria": "Categoria", "Contagem": "Número de Vagas"},
             title="Distribuição de Vagas por Categoria no Mercado de Tecnologia Brasileiro",
             color="Categoria",  # Adiciona cores diferentes para cada categoria
             color_discrete_sequence=px.colors.qualitative.Pastel)

fig.update_layout(xaxis_title="Categoria", 
                 yaxis_title="Número de Vagas",
                 xaxis={'categoryorder':'total descending'})  # Ordena as categorias por contagem
fig.show()

In [930]:
# Distribuição de Vagas por Senioridade
# Primeiro criamos um DataFrame com as contagens
contagens = df["Senioridade"].value_counts().reset_index()
contagens.columns = ["Senioridade", "Contagem"]  # Renomeando as colunas para maior clareza

# Criando o gráfico
fig = px.bar(contagens, 
             x="Senioridade", 
             y="Contagem",
             labels={"Categoria": "Senioridade", "Contagem": "Número de Vagas"},
             title="Distribuição de Vagas por Senioridade no Mercado de Tecnologia Brasileiro",
             color="Senioridade",  # Adiciona cores diferentes para cada Senioridade
             color_discrete_sequence=px.colors.qualitative.Pastel)

fig.update_layout(xaxis_title="Senioridade", 
                 yaxis_title="Número de Vagas",
                 xaxis={'categoryorder':'total descending'})  # Ordena Senioridade por contagem
fig.show()

In [931]:
# Distribuição de Vagas por modelo de trabalho
# Primeiro criamos um DataFrame com as contagens
contagens = df["modelo"].value_counts().reset_index()
contagens.columns = ["Modelo", "Contagem"]  # Renomeando as colunas para maior clareza

# Criando o gráfico
fig = px.bar(contagens, 
             x="Modelo", 
             y="Contagem",
             labels={"Categoria": "Modelo", "Contagem": "Número de Vagas"},
             title="Distribuição de Vagas por Modelo de Trabalho no Mercado de Tecnologia Brasileiro",
             color="Modelo",  # Adiciona cores diferentes para cada Modelo
             color_discrete_sequence=px.colors.qualitative.Pastel)

fig.update_layout(xaxis_title="Modelo", 
                 yaxis_title="Número de Vagas",
                 xaxis={'categoryorder':'total descending'})  # Ordena Modelo por contagem
fig.show()

### Habilidades mais demandadas

In [932]:
# Top 10 Habilidades Mais Requisitadas
# Somar as colunas de habilidades agrupando por categoria
habilidades_soma = df[cols_habilidades].sum().sort_values(ascending=False)
# Selecionar as 10 mais comuns
top_habilidades = habilidades_soma.head(10).reset_index()
top_habilidades.columns = ["Habilidade", "Contagem"]  # Renomeando as colunas para maior clareza
# Criando o gráfico
fig = px.bar(top_habilidades, 
             x="Habilidade", 
             y="Contagem",
             labels={"Habilidade": "Habilidade", "Contagem": "Número de Vagas"},
             title="Top 10 Habilidades Mais Requisitadas no Mercado de Tecnologia Brasileiro",
             color="Habilidade",  # Adiciona cores diferentes para cada habilidade
             color_discrete_sequence=px.colors.qualitative.Pastel)
fig.update_layout(xaxis_title="Habilidade", 
                 yaxis_title="Número de Vagas",
                 xaxis={'categoryorder':'total descending'})  # Ordena habilidades por contagem
fig.show()

In [933]:
# Criar um DataFrame com o Top 5 habilidades por categoria
top_habilidades_por_categoria = []

for categoria in df["Categoria"].unique():
    df_categoria = df[df["Categoria"] == categoria]
    habilidades_cols = [col for col in df_categoria.columns if col in habilidades_tecnicas]
    
    if habilidades_cols:
        contagem = df_categoria[habilidades_cols].sum().sort_values(ascending=False).head(5)
        for habilidade, count in contagem.items():
            top_habilidades_por_categoria.append({
                "Categoria": categoria,
                "Habilidade": habilidade,
                "Contagem": count
            })

df_top5 = pd.DataFrame(top_habilidades_por_categoria)

fig = px.bar(
    df_top5,
    x="Categoria",
    y="Contagem",
    color="Habilidade",
    title="Top 5 Habilidades Mais Demandadas por Categoria (Empilhado)",
    labels={"Contagem": "Número de Vagas", "Categoria": "Categoria"},
    color_discrete_sequence=px.colors.qualitative.Pastel,
)

# Melhorar layout
fig.update_layout(
    barmode="stack",  # Barras empilhadas
    xaxis_title="Categoria",
    yaxis_title="Número de Vagas",
    legend_title="Habilidade",
    hovermode="x unified",  # Mostrar tooltip unificado ao passar o mouse
    xaxis={'categoryorder': 'total descending'},  # Ordenar categorias pela maior demanda total
)

fig.show()

### Sankey de categorias e senioridade

In [934]:
# Sankey com porcentagens relativas de senioridade por categoria
df_sankey_senioridade = df.groupby(["Categoria", "Senioridade"]).size().reset_index(name="Count")

# Calcular totais por categoria
totais_categoria = df_sankey_senioridade.groupby("Categoria")["Count"].sum().reset_index()
df_sankey_senioridade = df_sankey_senioridade.merge(totais_categoria, on="Categoria", suffixes=('', '_total'))

# Calcular porcentagens relativas
df_sankey_senioridade["Porcentagem"] = (df_sankey_senioridade["Count"] / df_sankey_senioridade["Count_total"] * 100).round(2)

unique_categorias_sankey = df_sankey_senioridade["Categoria"].unique()
unique_senioridades_sankey = df_sankey_senioridade["Senioridade"].unique()

all_nodes_sankey = np.concatenate((unique_categorias_sankey, unique_senioridades_sankey))
label_map_sankey = {label: i for i, label in enumerate(all_nodes_sankey)}

# Modificar labels para incluir informações
node_labels = []
for node in all_nodes_sankey:
    if node in unique_categorias_sankey:
        total_cat = df_sankey_senioridade[df_sankey_senioridade["Categoria"] == node]["Count_total"].iloc[0]
        node_labels.append(f"{node}<br>({total_cat} vagas)")
    else:
        node_labels.append(node)

source_sankey = [label_map_sankey[cat] for cat in df_sankey_senioridade["Categoria"]]
target_sankey = [label_map_sankey[sen] for sen in df_sankey_senioridade["Senioridade"]]
value_sankey = df_sankey_senioridade["Porcentagem"].tolist()

fig = go.Figure(data=[go.Sankey(
    node=dict(
        pad=15,
        thickness=20,
        line=dict(color="black", width=0.5),
        label=node_labels,
    ),
    link=dict(
        source=source_sankey,
        target=target_sankey,
        value=value_sankey,
        hovertemplate='%{source.label} → %{target.label}<br>%{value}% da categoria<extra></extra>',
    )
)]).update_layout(
    title_text="Distribuição de Senioridade por Categoria (em %)",
    font_size=10
)
fig.show()

In [935]:
# Gráfico de distribuição de vagas por categoria e senioridade
fig_vagas = px.bar(
    Calc_Cand_Vaga_cat,
    x="Categoria",
    y="Quantidade_Vagas",
    color="Senioridade",
    title="Distribuição de Vagas por Categoria e Senioridade",
    labels={"Quantidade_Vagas": "Número de Vagas", "Categoria": "Categoria"},
    barmode="group",
    color_discrete_sequence=px.colors.qualitative.Pastel
)

fig_vagas.update_layout(
    xaxis_title="Categoria",
    yaxis_title="Número de Vagas",
    xaxis={'categoryorder': 'total descending'}
)
fig_vagas.show()

In [936]:
# Gráfico de distribuição de candidaturas por vaga por categoria e senioridade
fig_vagas = px.bar(
    Calc_Cand_Vaga_cat,
    x="Categoria",
    y="Cand_Vaga",
    color="Senioridade",
    title="Distribuição de Candidaturas por Vaga por Categoria e Senioridade",
    labels={"Cand_Vaga": "Número de Candidaturas por Vaga", "Categoria": "Categoria"},
    barmode="group",
    color_discrete_sequence=px.colors.qualitative.Pastel
)

fig_vagas.update_layout(
    xaxis_title="Categoria",
    yaxis_title="Número de Candidaturas por Vaga",
    xaxis={'categoryorder': 'total descending'}
)
fig_vagas.show()

In [937]:
df.to_csv('vagas_tech_limpa.csv')